### ISSUE TITLE
ovs-vsctl find cannot recognize space in the port name on Windows

### ISSUE THREAD

**Issue by linyinvmware** [openvswitch/ovs-issues#106]
There is an inconsistency between how ovs-vsctl "add-port" and "find" treats space in the port name on Windows platform.
Command 1: ovs-vsctl add-port bridge1 "Ethernet 1"
Command 2: ovs-vsctl find port name="Ethernet 1"  
Command 3: ovs-vsctl find port name="Ethernet\ 1" 

If command 1 is used to create the port, then command 2 cannot find the port. Instead, command 3 should be used in order to find the port. Basically port names need to have all there spaces escaped in the find command. The inconsistency is causing trouble if these commands are used in automation scripts or any program.

**Comment by blp** [comment]
I don't see how this could be an OVS bug.  OVS isn't in charge of how the command line is broken up into individual arguments; that's the job of the shell or, on Windows, the C library.

**Comment by linyinvmware** [comment]
Isn't getopt equivalent part of the ovs-vsctl code? Since we are not using GNU standard argument syntax here, I think the fix should be with the parser that ovs-vsctl used, in order to correctly understand the syntax, such as name="xxx xxx".

From user's perspective, the following two syntax are defined and claimed to be understood by ovs-vsctl:
ovs-vsctl add port <bridge-name> <port-name>
ovs-vsctl find port name="<port-name>"

Even though the same port name (with exactly the same format) is passed onto them, the second one complains an error. If the second syntax was not correctly supported, then the syntax should either be redefined or the parser need to make a little more efforts to understand it.

**Comment by linyinvmware** [comment]
Some bracketed strings were screened. Reposting the commands I typed:
ovs-vsctl add-port bridge port-name
ovs-vsctl find port name="port-name"

**Comment by blp** [comment]
> Isn't getopt equivalent part of the ovs-vsctl code?
> getopt doesn't break a string into arguments, it parses the arguments into semantics. It's the shell or the C library's job to break the command line string into arguments, if it's not doing what you expect then you need to change that code, not OVS (or understand how your shell or C library works and adapt to it).

**Comment by linyinvmware** [comment]
Thanks Ben for the suggestions! However, this bug is not specific to any shell. Both cygwin, Windows native shell, and Popen call from c++ fails the same command. To explain this issue better, let's run the following script test.bat in a Windows shell (either cygwin or standard command line):
=========script begin==========
@echo off
echo %1
echo %2
=========script end============

Here is the result:
F:\nsx-colibri\nsx-dev-testing>echo name="hello world"
name
"hello world"

As you can see, this is the correct behavior if a script/executable is written in the right way. The reason why ovs-vsctl is failing totally depend on how this ovs-vsctl.exe reads the parameter from the buffer and parses it. It has nothing to do with which shell being used at all.

I have also reproduced the same issue with cygwin envrionment. So I believe ovs-vsctl will misbehave on Unix systems as well. I can find some time to verify it. If you think this is a shell issue, then please let me know the right shell/command line combination that would work while taking exactly the same port name that contains a space.

**Comment by blp** [comment]
OK, I finally see what you mean.

This isn't a bug.  It's documented.  See ovs-vsctl(8):

```
 Database Values

   Each column in the database accepts a fixed type  of  data.   The  cur‐
   rently defined basic types, and their representations, are:

   integer
          A decimal integer in the range -2**63 to 2**63-1, inclusive.

   real   A floating-point number.

   Boolean
          True or false, written true or false, respectively.

   string An  arbitrary  Unicode  string,  except  that null bytes are not
          allowed.  Quotes are optional for most strings that  begin  with
          an  English  letter  or  underscore and consist only of letters,
          underscores, hyphens, and periods.  However, true and false  and
          strings  that  match  the  syntax  of  UUIDs (see below) must be
          enclosed in double quotes to distinguish them from  other  basic
          types.   When  double  quotes  are  used,  the syntax is that of
          strings in JSON, e.g. backslashes may be used to escape  special
          characters.   The  empty string must be represented as a pair of
          double quotes ("").

   UUID   Either a universally unique identifier in the style of RFC 4122,
          e.g.  f81d4fae-7dec-11d0-a765-00a0c91e6bf6,  or an @name defined
          by a get or create command within the same ovs-vsctl invocation.

   Multiple values in a single column may be separated by spaces or a sin‐
   gle  comma.   When  multiple  values  are  present,  duplicates are not
   allowed, and order is not important.  Conversely, some database columns
   can have an empty set of values, represented as [], and square brackets
   may optionally enclose other non-empty sets or single values as well.

   A few database columns are ``maps'' of key-value pairs, where  the  key
   and  the  value are each some fixed database type.  These are specified
   in the form key=value, where key and value follow the  syntax  for  the
   column's  key  type  and value type, respectively.  When multiple pairs
   are present (separated by spaces or a comma), duplicate  keys  are  not
   allowed,  and  again  the order is not important.  Duplicate values are
   allowed.  An empty map is represented as {}.  Curly braces may  option‐
   ally  enclose  non-empty  maps  as  well (but use quotes to prevent the
   shell  from  expanding  other-config={0=x,1=y}  into   other-config=0=x
   other-config=1=y, which may not have the desired effect).
```

**Comment by aserdean** [comment]
Closing it since this is documented
