### ISSUE TITLE
build rpm error in Centos 6.5

### ISSUE THREAD

**Issue by justlinux2010** [openvswitch/ovs-issues#107]
Hi,all
  I want to build the newest openvswitch in CentOS 6.5. I followed the steps in INSTALL.RHEL.md, but when i execute the command "rpmbuild -bb rhel/openvswitch.spec",got such errors:
     + install -D -m 0644 rhel/usr_share_openvswitch_scripts_sysconfig.template /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/openvswitch/scripts/sysconfig.template
- rm /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/bin/ovs-testcontroller /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/man/man8/ovs-testcontroller.8 /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/bin/ovs-test /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/bin/ovs-l3ping /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/man/man8/ovs-test.8 /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/man/man8/ovs-l3ping.8 /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/sbin/ovs-vlan-bug-workaround /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/man/man8/ovs-vlan-bug-workaround.8 /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/bin/ovn-controller /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/bin/ovn-controller-vtep /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/bin/ovn-docker-overlay-driver /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/bin/ovn-docker-underlay-driver /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/bin/ovn-nbctl /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/bin/ovn-northd /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/bin/ovn-sbctl /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/man/man5/ovn-nb.5 /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/man/man5/ovn-sb.5 /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/man/man7/ovn-architecture.7 /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/man/man8/ovn-controller-vtep.8 /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/man/man8/ovn-controller.8 /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/man/man8/ovn-ctl.8 /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/man/man8/ovn-nbctl.8 /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/man/man8/ovn-northd.8 /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/man/man8/ovn-sbctl.8 /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/openvswitch/ovn-nb.ovsschema /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/openvswitch/ovn-sb.ovsschema /root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/share/openvswitch/scripts/ovn-ctl
  rm: cannot remove `/root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/bin/ovs-test': No such file or directory
  rm: cannot remove`/root/rpmbuild/BUILDROOT/openvswitch-2.5.90-1.x86_64/usr/bin/ovs-l3ping': No such file or directory
  error: Bad exit status from /var/tmp/rpm-tmp.kJhjFD (%install)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.kJhjFD (%install)

  Can anyone help? Thanks

**Comment by shettyg** [comment]
openvswitch needs python 2.7. It is likely that you don't have it installed in centos 6.5?
