### ISSUE TITLE
Bug: Tunneling requires manual config in each VM

### ISSUE THREAD

**Issue by Samuel-Ghinet** [openvswitch/ovs-issues#11]
In order for tunneling to work, the mtu must be configured in every VM (by the client / user of the VM) to account for max additional bytes added by encapsulation protocol(s).

Also, any mtu change that the user / client may do in his OS (VM) may break tunneling functionality.

For production, we cannot:
a) expect the users of the VMs to change the MTU
b) allow the users to break tunneling by making changes in their configuration.

Expected functionality:
If original_packet_size + encap_size > external_nic_mtu => must:
a) encapsulate then fragment the buffer (if the payload ip header has not DF set)
b) send icmp4 error back to the VM if ipv4 and DF is set
c) send icmp6 error back to the VM if ipv6

**Comment by ankursh** [comment]
Is this issue same as https://github.com/openvswitch/ovs-issues/issues/9 ?

**Comment by ssp0** [comment]
I think it is, marking as duplicate.

**Comment by Samuel-Ghinet** [comment]
This issue I had presented shares some similarity to #9.
I will close this one and add its details as comment into #9.
