### ISSUE TITLE
Hyper-V host BSODs when OVS extension is enabled on vSwitch connected to a NIC team

### ISSUE THREAD

**Issue by mantri** [openvswitch/ovs-issues#111]
Sorry for the duplication. I am creating this new issue because I could not re-open #78 

The poweshell log transcript :

[ovs_setup_log.txt](https://github.com/openvswitch/ovs-issues/files/185183/ovs_setup_log.txt)

BSOD screenshot:

<img width="990" alt="screen shot 2016-03-22 at 3 44 04 pm" src="https://cloud.githubusercontent.com/assets/1046032/13971497/f7dab7a0-f04d-11e5-8ac8-884fe4a4ff3f.png">

**Comment by sairamvg** [comment]
@mantri OVS Hyper-V no longer uses the hardcoded "external.1" and "internal" names for the port. Refer to the latest documentation at [INSTALL.Windows.md](https://github.com/openvswitch/ovs/blob/master/INSTALL.Windows.md#steps-to-run-the-user-processes--configure-ports). This is the associated change - https://github.com/openvswitch/ovs/commit/9f760fd8213cb9e9521fbbc1e68661c3758e79c3. It will be helpful if you could mention which version of OVS you are running.

**Comment by mantri** [comment]
I ran the OVS from https://www.cloudbase.it/downloads/openvswitch-hyperv-installer-beta.msi

**Comment by mantri** [comment]
@sairamvg: From the documentation:

> Note:
>  Currently, we assume that the Hyper-V switch on which OVS extension is enabled has a single physical NIC connected to it.

Is there a plan to support NIC team?

**Comment by nithinrajub** [comment]
Hemanth, yes, Alin has patches pending review.

Pls. use the installer from the OVS codebase. You can build it.

The one from cloud base's website is pretty old.,

**Comment by mantri** [comment]
Thanks for the update @nithinrajub . Can you please keep this issue open to reference Alin's commit to support NIC teams? If not, please point me to the issue so that I can subscribe to it. Thanks in advance.

**Comment by aserdean** [comment]
The patches can be found under:
http://patchwork.ozlabs.org/patch/596674/
http://patchwork.ozlabs.org/patch/596675/
http://patchwork.ozlabs.org/patch/596675/
I'll close this issue once they are in, or reference them in the next patch respin (if needed) so you will get updates.

Again please file questions about our installer under: http://ask.cloudbase.it/questions/.

**Comment by mantri** [comment]
@aserdean : Thanks a lot!

**Comment by aserdean** [comment]
@mantri it took a while but patches got in:
https://github.com/openvswitch/ovs/commit/cd30b3460ac53719a6b8aaaba89b29c0304ac335
https://github.com/openvswitch/ovs/commit/da467899ab6e67b645840195a64600d1484d0dce
https://github.com/openvswitch/ovs/commit/a0c03adff6c23da64797ce087747f89f56cf2585

Please feel free to try the NetLBFO counterpart as well.

I am closing this issue at the moment, please feel free to reopen it if you encounter any issues.
