### ISSUE TITLE
Find alternative for WSAPoll() on Windows

### ISSUE THREAD

**Issue by yinlin09** [openvswitch/ovs-issues#117]
Right now, if a controller is set using "ovs set-manager" command, ovsdb-server will consumer 100% of a CPU core if the controller is offline. The 100% CPU has also been observed when other OVS daemons are temporarily unavailable.

The root cause of it is that WSAPoll() is buggy and do not exactly emulate poll() in POSIX. Basically, the function will NOT report a failed connection and will return EAGAIN instead of an error code even when the connection has already completed and failed.

A similar story has been reported here: https://daniel.haxx.se/blog/2012/10/10/wsapoll-is-broken/ and Microsoft decides to resolve it as a "won't fix".

The reason it causes 100% CPU usage rate is that the connection has already failed but we do not recognize it in check_connection_completion and will continue to call poll_fd_wait on the tcp socket, which cause poll_block() to always return immediately because the socket FD_CONNECT event will always trigger.

**Comment by shettyg** [comment]
CC @sairamvg

**Comment by shettyg** [comment]
CC @aserdean

**Comment by aserdean** [comment]
Patch applied.
