### ISSUE TITLE
OVS in Hyper-V windows server 2012R2, with OpenDaylight set_manager failed

### ISSUE THREAD

**Issue by lior-b** [openvswitch/ovs-issues#118]
I’m trying to install OVS on hyper-V and to configure it to use OpenDaylight as its OVSDB manager.
The OVS fail to connect to the ODL and I see the following errors in the OVS log:

2016-12-13T22:33:20.262Z|265117|netdev_windows|ERR|Call to GetAdaptersAddresses failed with error: The file name is too long.
2016-12-13T22:33:20.262Z|265118|in_band|WARN|br-int: cannot find route for controller (10.0.43.69): No such device or address

I tried to track down the error in the code and I suspect there is a problem with this part(ovs/lib/netdev-windows.c – see below)
When GetAdaptersAddresses is first being called, all_addr is NULL.
According to Microsoft documentation in this case  ERROR_BUFFER_OVERFLOW(111 ) is returned.
However the code check for ERROR_INSUFFICIENT_BUFFER(122) instead.
Is this something that you guys are familiar with?
Am I testing incorrectly or do you see any flaw in my analysis?
Obviously the consequences are that the OVS can’t communicate with OpenDaylight and the flow halts.

Will appreciate your response!

Lior

static int
	netdev_windows_get_next_hop(const struct in_addr *host,
	                            struct in_addr *next_hop,
	                            char **netdev_name)
	{
	    uint32_t ret_val = 0;
	    /* The buffer length of all addresses */
	    uint32_t buffer_length = 1000;
	    PIP_ADAPTER_ADDRESSES all_addr = NULL;
	    PIP_ADAPTER_ADDRESSES cur_addr = NULL;
	
	    ret_val = GetAdaptersAddresses(AF_INET,
	                                   GAA_FLAG_INCLUDE_PREFIX |
	                                   GAA_FLAG_INCLUDE_GATEWAYS,
	                                   NULL, all_addr, &buffer_length);
	
	    if (ret_val != ERROR_INSUFFICIENT_BUFFER ) {
	        VLOG_ERR("Call to GetAdaptersAddresses failed with error: %s",
	                 ovs_format_message(ret_val));
	        return ENXIO;
	    }
…

**Comment by lior-b** [comment]
Patch submitted by Alin for this issue:
http://patchwork.ozlabs.org/patch/705499/
Pending testing.

**Comment by aserdean** [comment]
Fixed with commit: https://github.com/openvswitch/ovs/commit/e83cb65878fb2ff3de8eaeee0970d0fc9ba104b2
