### ISSUE TITLE
Fix the history of files under ovs/Documentation/intro/install/

### ISSUE THREAD

**Issue by shashankram** [openvswitch/ovs-issues#119]
Documentation files under ovs/Documentation/intro/install/ have been moved, and the history of these files have been lost. For eg, the original authors, the commits which added the documentation etc. An example of this is ovs/Documentation/intro/install/windows.rst. In the future, it would be good to preserve the history for identifying when an issue, such as a mistake in the documentation was introduced and so on.

**Comment by blp** [comment]
What actual action do you want us to take?

**Comment by russellb** [comment]
Sure, it would have been ideal to make sure they were all moves instead of delete/add.  I'm not sure any of that is fixable at this point, though.

**Comment by shashankram** [comment]
Since nothing can be done right now, closing the issue.
