### ISSUE TITLE
Link to Windows coding-style document is broken

### ISSUE THREAD

**Issue by shashankram** [openvswitch/ovs-issues#120]
The link to the Windows coding-style document is broken in https://github.com/openvswitch/ovs/blob/34aa9cf97e2c5c937296012183dea5862a2b6190/Documentation/internals/contributing/coding-style.rst#id1

**Comment by blp** [comment]
It works fine as rendered at http://docs.openvswitch.org/en/latest/internals/contributing/coding-style/.

**Comment by shashankram** [comment]
Thanks Ben. Do we intend to not support the rendering on github? My issue was more around the fact that the hyperlink https://github.com/openvswitch/ovs/blob/34aa9cf97e2c5c937296012183dea5862a2b6190/Documentation/internals/contributing/coding-style.rst#id1 should have been http://docs.openvswitch.org/en/latest/internals/contributing/coding-style-windows/

**Comment by blp** [comment]
Documentation/internals/contributing/documentation-style.rst says not to use that form in top-level documents, but this is not a top-level document.

**Comment by stephenfin** [comment]
> Thanks Ben. Do we intend to not support the rendering on github? My issue was more around the fact that the hyperlink https://github.com/openvswitch/ovs/blob/34aa9cf97e2c5c937296012183dea5862a2b6190/Documentation/internals/contributing/coding-style.rst#id1 should have been http://docs.openvswitch.org/en/latest/internals/contributing/coding-style-windows/

Unfortunately GitHub only renders reStructuredText - not Sphinx directives like `doc` or `ref`. Like @blp mentioned, we consider this expected behavior for any file found found in `Documentation` such as this. I'd suggest using the [docs website](docs.openvswitch.org) instead (or building/browsing the docs locally with `make htmldocs` if offline).
