### ISSUE TITLE
ovs-windows: Port entry should show an error when incorrectly created if "ovs-vsctl add-port" command fails

### ISSUE THREAD

**Issue by shashankram** [openvswitch/ovs-issues#125]
On Windows, if adding a port to the bridge fails, the port is still seen in OVSDB.

Eg,
root@WIN-HSF3PR0VR24 /cygdrive/c
$ ovs-vsctl.exe add-port br-int foo
ovs-vsctl: Error detected while setting up 'foo'.  See ovs-vswitchd log for details.

root@WIN-HSF3PR0VR24 /cygdrive/c
$ ovs-vsctl.exe show
73d38433-bb6d-4977-8b3c-93e8f3539d29
    Bridge br-pif
        Port "Ethernet1"
            Interface "Ethernet1"
        Port br-pif
            Interface br-pif
                type: internal
        Port Ethernet
            Interface Ethernet
    Bridge br-int
        Port "Ethernet 2"
            Interface "Ethernet 2"
        Port br-int
            Interface br-int
                type: internal
        Port foo
            Interface foo
    ovs_version: "2.6.0"

If the addition of port fails, it should be shown as an error in "ovs-vsctl show".

On Linux, the following error is correctly shown:
root@admin-vm:/home/adminu# ovs-vsctl add-br test
root@admin-vm:/home/adminu# ovs-vsctl add-port test foo
ovs-vsctl: Error detected while setting up 'foo'.  See ovs-vswitchd log for details.

    Bridge test
        Port foo
            Interface foo
                error: "could not open network device foo (No such device)"
        Port test
            Interface test
                type: internal
    ovs_version: "2.6.0.4507437"

**Comment by blp** [comment]
That's expected behavior on all platforms.  OVSDB expresses the desired state for the switch, and OVS attempts to configure the switch according to its contents, and if OVS fails then it just reports the error and the user is responsible for adjusting the environment (e.g. by creating a network device named foo) or the database (e.g. by deleting port foo) in some way.

**Comment by shashankram** [comment]
Hi, but on Windows, we do not see an error msg in "ovs-vsctl show". This should be fixed?

**Comment by blp** [comment]
> Hi, but on Windows, we do not see an error msg in "ovs-vsctl show". This should be fixed?

That does sound like a bug.  I hope that someone who works on the Windows datapath will take a look.

**Comment by aserdean** [comment]
I can't see any issues on master:

PS C:\Users\Administrator> ovs-vsctl.exe add-port br-int bla
ovs-vsctl: Error detected while setting up 'bla': could not add network device bla to ofproto (Invalid argument).  See o
vs-vswitchd log for details.
ovs-vsctl: The default log directory is "C:\Program Files (x86)\Open vSwitch\logs\".
PS C:\Users\Administrator> ovs-vsctl.exe show
c3a35fd8-f65a-4b7b-9bea-d8e495290049
    Bridge br-int
        Port vxlan
            Interface vxlan
                type: vxlan
                options: {in_key=flow, local_ip="13.13.13.1", out_key=flow, remote_ip="13.13.13.2"}
        Port bla
            Interface bla
                error: "could not add network device bla to ofproto (Invalid argument)"
        Port br-int
            Interface br-int
                type: internal
        Port vmfake
            Interface vmfake
                type: internal
    Bridge "br0"
        Port "eth0"
            Interface "eth0"
        Port "br0"
            Interface "br0"
                type: internal
PS C:\Users\Administrator> ovs-dpctl.exe show
system@ovs-system:
        lookups: hit:1601 missed:1081 lost:0
        flows: 0
        port 1: br0 (internal)
        port 2: eth0
        port 3: br-int (internal)
        port 4: vmfake (internal)
        port 5: vxlan_sys_4789 (vxlan)
PS C:\Users\Administrator> ovs-vsctl.exe --version
ovs-vsctl (Open vSwitch) 2.7.90
DB Schema 7.14.0
PS C:\Users\Administrator>

Feel free to open it, if your issue occurs on 2.7

**Comment by aserdean** [comment]
I saw that you are running on 2.6, so I investigated further and found the actual problem.
You can find the patch at: http://patchwork.ozlabs.org/patch/725504/

I tested on 2.5->2.7 and master. On 2.6 you will need to cherry-pick the following commit as well:
git cherry-pick 583d34678d32482d616fe5bd7dc323f044788898
(https://github.com/openvswitch/ovs/commit/583d34678d32482d616fe5bd7dc323f044788898)

Thanks for finding this! Please let me know if that patch fixes the problem.

**Comment by shashankram** [comment]
Thanks for the fix Alin!
