### ISSUE TITLE
ovsdb records consume too much memory

### ISSUE THREAD

**Issue by kuncao** [openvswitch/ovs-issues#130]
Hi every experts
I am newbie in OVS and ovsdb
I have a issue about ovsdb  and can not resolved by google the keys
detail information
I insert abort 1 Minllion records about comsume 6.3G
the insert script is as following:
cat ovsdb_sg_.py.back
import socket
import sys
from select import select
import Queue
import time
from concurrent import futures
import json
import datetime
import thread
import commands
monitor_lock=thread.allocate_lock()
OVSDB_IP = '127.0.0.1'
OVSDB_PORT = 6632
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((OVSDB_IP, OVSDB_PORT))

def listen_for_messages(sock, message_queues,id,section):
    global now1
    # To send something, add a message to queue and append sock to outputs
    inputs = [sock]
    outputs = []
    file_object = open('/home/djc/ovsdb_test.txt', 'w+')
    #/home/djc/ovsdb_test.txt for exceptions 
    section_ten = 100000
    while sock:
        try:
            readable, writable, exceptional = select(inputs, outputs, [])
            for s in readable:
                if s is sock:
                    data = sock.recv(4096)
                    file_object.write(data)
        except Exception, e :
            print e
            file_object.write(str(e))
            exit(1)

def insert_rule(id, section):
    global s
    rule_id = 0

    #select_item = {"op":"select","where":[],"table":"Ip_Bond_Remote_Security_Group"}
    
    #list_dbs_query = {"method":"transact", "params":["cfg",{"op":"select","where":[],"table":"Security_group_associated_info"}],"id":"99c60881-cf5c-4f5d-8c13-95e7c90aba9e"}
    id = 0
    count = 1000000
    list_dbs_insert = {"method":"transact", "params":["cfg"], "id":10}
    for i in range(count):
        i = str(i)
        print i
        insert_item = {"op":"insert","row":{"tenant_id":"e3387782-ba02-49f0-a629-8be6b1fe703f","remote_group_id":"7de428f8-5a98-4d9c-90b0-1d8707bf00ab","protocol":6,"ether_type":"IPv4","name":i,"port_range":["map",[["port_range_max",22],["port_range_min",22]]],"direction":"ingress"},"table":"Security_Group_Rule"}
        # insert item 
        list_dbs_insert["params"].append(insert_item)
    with monitor_lock:
        s.send(json.dumps(list_dbs_insert))
        data = s.recv(6000000)
        print data
    print "END"
   
def send_echo(s):
    while True:
        list_dbs_query = {"method": "echo", "params": [], "id": 1}
        time.sleep(0.5)
        with monitor_lock:
            s.send(json.dumps(list_dbs_query))

#destroy Security_Group_Rule
#cmd_destroy="ovsdb-client transact '[\"cfg\",{\"op\":\"delete\",\"table\":\"Security_Group\",\"where\":[]}]'"
#cmd_destroy = "ovs-vsctl --db_name=cfg destroy Security_Group_Rule"
#ret1,output1 = commands.getstatusoutput(cmd_destroy)

id = 1
section = 1000000
message_queues = {}
message_queues[s] = Queue.Queue()
threadpool = futures.ThreadPoolExecutor(max_workers=5)
threadpool.submit(listen_for_messages, s, message_queues,id ,section)
threadpool.submit(send_echo, s)
now1 = datetime.datetime.utcnow()
insert_rule(id,section)
time.sleep(10000)

**Comment by kuncao** [comment]
/usr/local/CE1800V-python/bin/python  /mypath/ovsdb_sg_.py.back

**Comment by kuncao** [comment]
memory comsume information
Tasks: 334 total,   4 running, 329 sleeping,   0 stopped,   1 zombie
%Cpu(s):  4.6 us,  8.4 sy,  0.0 ni, 87.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 49286084 total, 13348148 free, 28296140 used,  7641796 buff/cache
KiB Swap:  4194300 total,  4194300 free,        0 used. 18033348 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                           
                                                                                                            
12901 ce1800v   10 -10  597684 143368  13068 S   3.7  0.3 140:00.93 ovs-vswitchd                                                                                                      
12889 ce1800v   10 -10 6634716 6.263g   1984 S   0.7 13.3  26:51.31 ovsdb-server

**Comment by blp** [comment]
How big is your data?  OVSDB is an in-memory database: every record in the database is held in memory.

**Comment by kuncao** [comment]
my record is about 500M,but ovsdb-server is about 6.3G

**Comment by blp** [comment]
That's probably too much data for OVSDB in any case.  I'd encourage you to use a database that is designed for larger amounts of data.

**Comment by kuncao** [comment]
import socket
import sys
from select import select
import Queue
import time
from concurrent import futures
import json
import datetime
import thread
import commands
monitor_lock=thread.allocate_lock()
OVSDB_IP = '127.0.0.1'
OVSDB_PORT = 6632
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((OVSDB_IP, OVSDB_PORT))

def listen_for_messages(sock, message_queues,id,section):
    global now1
    # To send something, add a message to queue and append sock to outputs
    inputs = [sock]
    outputs = []
    file_object = open('/home/kangxu/ovsdb_test.txt', 'w')
    section_ten = 100000
    while sock:
        try:
            readable, writable, exceptional = select(inputs, outputs, [])
            for s in readable:
                if s is sock:
                    data = sock.recv(4096)
                    if str(data).find(str(id+section_ten)) != -1:
                        print str(section_ten)+":"
                        file_object.write(str(data))
                        now2 = datetime.datetime.utcnow()
                        print now1, now2
                        second = round(float((now2 - now1).total_seconds()), 5)
                        print "second:"+str(second)
                        now1 = datetime.datetime.utcnow()
                        section_ten = section_ten + 100000
                        print
        except Exception, e :
            print e
            file_object.write(str(e))
            exit(1)

def insert_rule(id, section):
    global s
    over_id = id + section
    while True:
        list_dbs_query =  {"method":"transact", "params":["cfg",{"uuid-name":"row1902cfe0_eeb5_4b58_826e_707089a2830f","op":"insert","table":"Security_Group_Rule","row":{"name":"rule"+str(id),"direction":"egress","ether_type":"IPv4","protocol":1,"remote_ip_prefix":"192.168.10.22"}}], "id": id}
        with monitor_lock:
            s.send(json.dumps(list_dbs_query))
        id = id + 1
        if id == over_id+1:
            time.sleep(864000)

def send_echo(s):
    while True:
        list_dbs_query = {"method": "echo", "params": [], "id": 1}
        time.sleep(0.5)
        with monitor_lock:
            s.send(json.dumps(list_dbs_query))

#destroy Security_Group_Rule
cmd_destroy="ovsdb-client transact '[\"cfg\",{\"op\":\"delete\",\"table\":\"Security_Group_Rule\",\"where\":[]}]'"
#cmd_destroy = "ovs-vsctl --db_name=cfg destroy Security_Group_Rule"
ret1,output1 = commands.getstatusoutput(cmd_destroy)

id = 1
section = 1000000
message_queues = {}
message_queues[s] = Queue.Queue()
threadpool = futures.ThreadPoolExecutor(max_workers=5)
threadpool.submit(listen_for_messages, s, message_queues,id ,section)
threadpool.submit(send_echo, s)
now1 = datetime.datetime.utcnow()
insert_rule(id,section)
time.sleep(1000)
--------
the above script insert one  record into ovsdb and insert 1 million times
and consume  about  1.3 G memory
