### ISSUE TITLE
ovsdb-server's memory continually increase and keep at a value even drop all the record

### ISSUE THREAD

**Issue by kuncao** [openvswitch/ovs-issues#131]
the following python script is for insert into ovsdb
------
import socket
import sys
from select import select
import Queue
import time
from concurrent import futures
import json
import datetime
import thread
import commands
monitor_lock=thread.allocate_lock()
OVSDB_IP = '127.0.0.1'
OVSDB_PORT = 6632
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((OVSDB_IP, OVSDB_PORT))

def listen_for_messages(sock, message_queues,id,section):
    global now1
    # To send something, add a message to queue and append sock to outputs
    inputs = [sock]
    outputs = []
    file_object = open('/home/kangxu/ovsdb_test.txt', 'w')
    section_ten = 100000
    while sock:
        try:
            readable, writable, exceptional = select(inputs, outputs, [])
            for s in readable:
                if s is sock:
                    data = sock.recv(4096)
                    if str(data).find(str(id+section_ten)) != -1:
                        print str(section_ten)+":"
                        file_object.write(str(data))
                        now2 = datetime.datetime.utcnow()
                        print now1, now2
                        second = round(float((now2 - now1).total_seconds()), 5)
                        print "second:"+str(second)
                        now1 = datetime.datetime.utcnow()
                        section_ten = section_ten + 100000
                        print
        except Exception, e :
            print e
            file_object.write(str(e))
            exit(1)

def insert_rule(id, section):
    global s
    over_id = id + section
    while True:
        list_dbs_query =  {"method":"transact", "params":["cfg",{"uuid-name":"row1902cfe0_eeb5_4b58_826e_707089a2830f","op":"insert","table":"Security_Group_Rule","row":{"name":"rule"+str(id),"direction":"ingress","ether_type":"IPv4","protocol":6}}], "id": id}
        with monitor_lock:
            s.send(json.dumps(list_dbs_query))
        id = id + 1
        if id == over_id+1:
            time.sleep(864000)

def send_echo(s):
    while True:
        list_dbs_query = {"method": "echo", "params": [], "id": 1}
        time.sleep(0.5)
        with monitor_lock:
            s.send(json.dumps(list_dbs_query))

#destroy Security_Group_Rule
cmd_destroy="ovsdb-client transact '[\"cfg\",{\"op\":\"delete\",\"table\":\"Security_Group_Rule\",\"where\":[]}]'"
#cmd_destroy = "ovs-vsctl --db_name=cfg destroy Security_Group_Rule"
ret1,output1 = commands.getstatusoutput(cmd_destroy)

id = 1
section = 1000000
message_queues = {}
message_queues[s] = Queue.Queue()
threadpool = futures.ThreadPoolExecutor(max_workers=5)
threadpool.submit(listen_for_messages, s, message_queues,id ,section)
threadpool.submit(send_echo, s)
now1 = datetime.datetime.utcnow()
insert_rule(id,section)
time.sleep(1000)

**Comment by kuncao** [comment]
top | grep ovsdb-server
os:centos7.1
18632 ce1800v   10 -10  127040  59064   1964 R 100.0  0.1   0:04.40 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  231652 162996   1964 R  99.7  0.2   0:07.41 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  231652 162996   1964 R 100.0  0.2   0:10.43 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  232180 163256   1964 R  99.7  0.2   0:13.43 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  275884 207080   1964 R 100.0  0.2   0:16.44 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  320548 251696   1964 R 100.0  0.3   0:19.45 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  364900 296048   1964 R 100.0  0.3   0:22.46 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  409384 340664   1964 R  99.7  0.3   0:25.47 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  454672 385808   1964 R 100.0  0.4   0:28.48 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  500284 431480   1964 R 100.0  0.4   0:31.49 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  544108 475304   1964 R 100.0  0.5   0:34.50 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1776540 1.630g   1964 R  99.7  1.7   0:37.51 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1970168 1.803g   1964 R 100.0  1.9   0:40.52 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  610468 532668   1964 R 100.0  0.5   0:43.53 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  610980 532928   1964 R  99.7  0.5   0:46.53 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  611492 533456   1964 R 100.0  0.5   0:49.54 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  628916 550880   1964 R 100.0  0.6   0:52.55 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  655012 577016   1964 R 100.0  0.6   0:55.57 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  699496 621368   1964 R  99.7  0.6   0:58.57 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  745348 667284   1964 R 100.0  0.7   1:01.58 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  789568 711636   1964 R 100.0  0.7   1:04.59 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  833656 755724   1964 R 100.0  0.8   1:07.60 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  878512 800604   1964 R 100.0  0.8   1:10.61 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  922204 844164   1964 R 100.0  0.9   1:13.62 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10  966556 888516   1964 R 100.0  0.9   1:16.63 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1010776 932868   1964 R 100.0  0.9   1:19.64 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1054600 976428   1964 R  99.7  1.0   1:22.64 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1098028 996.1m   1964 R 100.0  1.0   1:25.66 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1141852 1.015g   1964 R 100.0  1.1   1:28.67 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1186336 1.057g   1964 R 100.0  1.1   1:31.68 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1231520 1.100g   1964 R 100.0  1.2   1:34.69 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1276004 1.143g   1964 R 100.0  1.2   1:37.70 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1320620 1.185g   1964 R 100.0  1.3   1:40.71 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1364708 1.227g   1964 R  99.7  1.3   1:43.72 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1409324 1.270g   1964 R  99.7  1.3   1:46.72 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1410776 1.271g   1964 S   4.0  1.3   1:46.84 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.7  1.3   1:46.86 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.3  1.3   1:46.87 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.3  1.3   1:46.88 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.3  1.3   1:46.89 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.3  1.3   1:46.90 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.3  1.3   1:46.91 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.3  1.3   1:46.92 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.3  1.3   1:46.93 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.3  1.3   1:46.94 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.7  1.3   1:46.96 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.3  1.3   1:46.97 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.3  1.3   1:46.98 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.7  1.3   1:47.00 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.7  1.3   1:47.02 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.7  1.3   1:47.04 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.3  1.3   1:47.05 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.3  1.3   1:47.06 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.3  1.3   1:47.07 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411040 1.271g   1964 S   0.3  1.3   1:47.08 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411176 1.271g   1964 S   0.7  1.3   1:47.10 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 1411176 1.271g   1964 S   0.7  1.3   1:47.12 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 2304496 2.133g   1964 R  79.1  2.3   1:49.50 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 3504812 3.278g   1964 R 100.0  3.5   1:52.51 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4354592 4.088g   1964 R  99.7  4.3   1:55.51 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 R 100.0  4.5   1:58.53 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 R 100.0  4.5   2:01.54 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S  39.2  4.5   2:02.72 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.7  4.5   2:02.74 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   1.0  4.5   2:02.77 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   1.0  4.5   2:02.80 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   1.3  4.5   2:02.84 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:02.85 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:02.86 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:02.87 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:02.88 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:02.89 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:02.90 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:02.91 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:02.92 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.7  4.5   2:02.94 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:02.95 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:02.96 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:02.97 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:02.98 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:02.99 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:03.00 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:03.01 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:03.02 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:03.03 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:03.04 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:03.05 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:03.06 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:03.07 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:03.08 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:03.09 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 D   0.3  4.5   2:03.10 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524960 4.242g   1964 R  99.3  4.5   2:06.09 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524960 4.242g   1964 R 100.0  4.5   2:09.10 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524960 4.242g   1964 R 100.0  4.5   2:12.11 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S  60.1  4.5   2:13.92 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   1.0  4.5   2:13.95 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:13.96 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   1.7  4.5   2:14.01 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.7  4.5   2:14.03 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.04 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.05 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.06 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.07 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.08 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.09 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.10 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.7  4.5   2:14.12 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.13 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.14 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.7  4.5   2:14.16 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.17 ovsdb-server

**Comment by kuncao** [comment]
ovsdb-client transact '["cfg",{"op":"delete","table":"Security_Group_Rule","where":[]}]'

the following information is after deleting all the records 
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.7  4.5   2:14.78 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.79 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.80 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.81 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.82 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.7  4.5   2:14.84 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.85 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.86 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.7  4.5   2:14.88 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.89 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.90 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.91 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.92 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.93 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.94 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.7  4.5   2:14.96 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.97 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.98 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:14.99 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:15.00 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:15.01 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:15.02 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:15.03 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:15.04 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:15.05 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4524956 4.242g   1964 S   0.3  4.5   2:15.06 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.07 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.08 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.09 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.10 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.11 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.12 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.13 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.14 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.15 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.7  4.3   2:15.17 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.18 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.19 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.7  4.3   2:15.21 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.7  4.3   2:15.23 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.24 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.25 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.7  4.3   2:15.27 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.28 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.29 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.30 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.7  4.3   2:15.32 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.33 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.34 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 S   0.3  4.3   2:15.35 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 R 100.0  4.3   2:18.36 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 R  99.7  4.3   2:21.36 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 R  99.7  4.3   2:24.37 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 R 100.0  4.3   2:27.38 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 R 100.0  4.3   2:30.39 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4369304 4.099g   1964 R 100.0  4.3   2:33.41 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 4370904 4.104g   1964 R 100.0  4.4   2:36.42 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5453436 5.136g   1964 R  99.7  5.4   2:39.42 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5623792 5.256g   1964 R 100.0  5.6   2:42.43 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 R  99.7  5.7   2:45.43 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 R 100.0  5.7   2:48.44 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 R 100.0  5.7   2:51.46 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S  66.4  5.7   2:53.46 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.47 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.48 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.49 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.50 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.51 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.52 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.53 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.54 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.55 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.56 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.57 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.58 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.59 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.60 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.61 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.62 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.63 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.64 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.65 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.66 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.67 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.68 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.69 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.70 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.71 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.72 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.73 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.74 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.75 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.76 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.77 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.78 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.79 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.7  5.7   2:53.81 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.82 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.83 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.84 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.85 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.86 ovsdb-server                                                                                                                               
18632 ce1800v   10 -10 5779440 5.363g   1964 S   0.3  5.7   2:53.87 ovsdb-server

**Comment by kuncao** [comment]
ovs-vsctl --version
ovs-vsctl (Open vSwitch) 2.5.0
Compiled Jun 10 2017 14:38:23
DB Schema 7.12.1

**Comment by xuxukang** [comment]
I am a friend of Kuncao. 
We added a cfg.conf.db database. There is a table called Security_Group_Rule in cfg.conf.db.
eg:   
#ps -ef | grep ovsdb-server
ce1800v  103323      1  2 11:25 ?        00:06:20 ovsdb-server /etc/openvswitch/conf.db /etc/openvswitch/cfg.conf.db -vconsole:emer -vsyslog:err .....

**Comment by blp** [comment]
Processes do not normally release memory once they have allocated it, even if they are no longer using most of it.

**Comment by xuxukang** [comment]
Is this a bug?

**Comment by xuxukang** [comment]
Can we fix it?  How? Which file to modify?

**Comment by blp** [comment]
Is what a bug?

**Comment by xuxukang** [comment]
It consumes too much memory,  Should it be so realized? Can we optimize?

**Comment by xuxukang** [comment]
Consuming memory code in which file?  I want to see the code, whether I can modify it, let it consume less memory

**Comment by xuxukang** [comment]
@blp

**Comment by blp** [comment]
It's hard to tell whether it's using too much memory.  If you think so, please feel free to analyze and debug the issue.

**Comment by xuxukang** [comment]
I insert 100w data, then all the data are deleted, the memory consumption does not decline but increased, this situation can not accept....... @blp

**Comment by blp** [comment]
Processes do not normally release memory once they have allocated it, even if they are no longer using most of it.  This is not an ovsdb-server issue, it is standard glibc behavior.  If you want it changed, file a bug against glibc.
