### ISSUE TITLE
Ovsdb processes do not normally release memory once they have allocated it. Is this a bug? 

### ISSUE THREAD

**Issue by xuxukang** [openvswitch/ovs-issues#132]
ovsdb
Processes do not normally release memory once they have allocated it, even if they are no longer using most of it.   ----by blp
Help! Is this a bug? Can we fix it? How? Which file to modify?

**Comment by russellb** [comment]
This looks like a follow-up to #131, so there's no reason to open a new issue for it.

I suggest using the mailing list instead of the bug tracker if you'd like to ask questions.  Thanks!

**Comment by xuxukang** [comment]
I see # 131 has been closed @russellb

**Comment by russellb** [comment]
Right ... we should probably close this one too and just move to the mailing list
