### ISSUE TITLE
Add vxlan port problems

### ISSUE THREAD

**Issue by myftcode** [openvswitch/ovs-issues#146]
[root@node1 network-scripts]# ovs-vsctl show
ec40e1a6-8907-4948-ac7e-45e82be5693c
    Bridge "br0"
        Port "br0"
            Interface "br0"
                type: internal
    ovs_version: "2.5.0"
[root@node1 network-scripts]# ovs-vsctl add-port br0 vxlan0 -- set interface vxlan0 type=vxlan options:remote_ip=10.0.2.12
ovs-vsctl: Error detected while setting up 'vxlan0'.  See ovs-vswitchd log for details.

[root@node1 network-scripts]# tail -3 /var/log/openvswitch/ovs-vswitchd.log 
2018-04-26T02:58:25.529Z|183395|dpif|WARN|system@ovs-system: failed to add vxlan0 as port: Address family not supported by protocol
2018-04-26T02:58:26.526Z|183396|dpif|WARN|Dropped 139 log messages in last 1 seconds (most recently, 0 seconds ago) due to excessive rate
2018-04-26T02:58:26.526Z|183397|dpif|WARN|system@ovs-system: failed to add vxlan0 as port: Address family not supported by protocol
[root@node1 network-scripts]#

**Comment by greenpau** [comment]
@myftcode, likely you have IPv6 disabled. What is you “ip addr show” say?

**Comment by blp** [comment]
Does your kernel include VXLAN support?

@greenpau I don't see any evidence that @myftcode is trying to use IPv6.

**Comment by greenpau** [comment]
> @greenpau I don't see any evidence that @myftcode is trying to use IPv6.

@blp , I had similar issues recently. I both GENEVE and VXLAN. See the explanation below. I sent an email to bugs@openvswitch.org.

*****

When IPv6 is disabled, e.g. in `/boot/grub2/grub.cfg`:

```
linux16 ... ipv6.disable=1
```

Then GENEVE interface does not come up properly. However, when IPv6 is enabled, then OVN tunnel interfaces work properly.

```
# ovs-vsctl show
        Port "ovn-14a54f-0"
            Interface "ovn-14a54f-0"
                type: geneve
                options: {csum="true", key=flow, remote_ip="10.10.10.10"}
                error: "could not add network device ovn-14a54f-0 to ofproto (Address family not supported by protocol)"
```

System info:

```
# cat /proc/version
Linux version 3.10.0-514.21.1.el7.x86_64 (mockbuild@x86-020.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Sat Apr 22 02:41:35 EDT 2017

# ovs-vswitchd --version
ovs-vswitchd (Open vSwitch) 2.9.0
```

**Comment by myftcode** [comment]
@greenpau Yes, it is my kernel that has disabled ipv6. When I sent the email today, it also gave me "address family error". I immediately thought of the error of openvswitch.

**Comment by blp** [comment]
@myftcode @greenpau Thanks for calling out the IPv6 relationship.  I put out a question to our kernel expert: https://mail.openvswitch.org/pipermail/ovs-discuss/2018-May/046649.html

**Comment by greenpau** [comment]
@blp, perhaps this output is related to the issue. See `_realsocket` call and notice the `socket.error: [Errno 97] Address family not supported by protocol`.

```
# make check TESTSUITEFLAGS='2414 2417 2423 2426'
make  check-recursive
make[1]: Entering directory `/opt/dev/ovs'
Making check in datapath
make[2]: Entering directory `/opt/dev/ovs/datapath'
make[3]: Entering directory `/opt/dev/ovs/datapath'
make[3]: Leaving directory `/opt/dev/ovs/datapath'
make[2]: Leaving directory `/opt/dev/ovs/datapath'
make[2]: Entering directory `/opt/dev/ovs'
make[3]: Entering directory `/opt/dev/ovs/datapath'
make[3]: `distfiles' is up to date.
make[3]: Leaving directory `/opt/dev/ovs/datapath'
make  utilities/ovs-appctl-bashcomp.bash utilities/ovs-vsctl-bashcomp.bash tests/atlocal tests/testpki-cacert.pem tests/testpki-cert.pem tests/testpki-privkey.pem tests/testpki-req.pem tests/testpki-cert2.pem tests/testpki-privkey2.pem tests/testpki-req2.pem
make[3]: Entering directory `/opt/dev/ovs'
make[3]: Nothing to be done for `utilities/ovs-appctl-bashcomp.bash'.
make[3]: Nothing to be done for `utilities/ovs-vsctl-bashcomp.bash'.
make[3]: `tests/atlocal' is up to date.
make[3]: `tests/testpki-cacert.pem' is up to date.
make[3]: `tests/testpki-cert.pem' is up to date.
make[3]: `tests/testpki-privkey.pem' is up to date.
make[3]: `tests/testpki-req.pem' is up to date.
make[3]: `tests/testpki-cert2.pem' is up to date.
make[3]: `tests/testpki-privkey2.pem' is up to date.
make[3]: `tests/testpki-req2.pem' is up to date.
make[3]: Leaving directory `/opt/dev/ovs'
make  check-local
make[3]: Entering directory `/opt/dev/ovs'
set /bin/sh './tests/testsuite' -C tests AUTOTEST_PATH=utilities:vswitchd:ovsdb:vtep:tests:::ovn/controller-vtep:ovn/northd:ovn/utilities:ovn/controller 2414 2417 2423 2426; \
"$@" || (test X'' = Xyes && "$@" -j1 --recheck)
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/usr/lib64/python2.7/socket.py", line 187, in __init__
    _sock = _realsocket(family, type, proto)
socket.error: [Errno 97] Address family not supported by protocol
```

**Comment by blp** [comment]
@greenpau The exception is harmless and expected if a system lacks IPv6, but I agree that it looks bad.  I sent a patch to avoid printing the exception: https://patchwork.ozlabs.org/patch/919415/

**Comment by blp** [comment]
I applied the fix to master.
