### ISSUE TITLE
Cloned packets may overwrite / break original packets

### ISSUE THREAD

**Issue by Samuel-Ghinet** [openvswitch/ovs-issues#15]
In packet cloning, the cloned packet and the original packet reference the same data / buffer.
This causes the original packet to be written over whenever an "action: set" is done on the packet.

Also, outputting a packet to multiple tunneling ports corrupts the packet for each tunnel.

Fix: whenever needed, packet duplication must be done instead.

**Comment by EitanEliahu** [comment]
Why the need for packet duplication whenonly the packet header is modified?

**Comment by Samuel-Ghinet** [comment]
If the packet contains only one MDL, then this is the only solution :)

**Comment by ssp0** [comment]
As per my comment on the mailing list (http://openvswitch.org/pipermail/dev/2014-August/043456.html), I already opened an issue #5. Can we close this, since it is already been tracked?

> If the packet contains only one MDL, then this is the only solution :)

That's not true at all. Please look at the buffer management API's and let us know if you are not convinced. :)

**Comment by Samuel-Ghinet** [comment]
Sorry, a bit of mistake from my side.
First, I did not see #5.

Second, the situation is a bit more complex. I'll try to give details in #5
