### ISSUE TITLE
set-ssl: terminating with signal 14 (Alarm clock)

### ISSUE THREAD

**Issue by greenpau** [openvswitch/ovs-issues#155]
While getting SSL configuration work no issue:

```bash
# ovn-nbctl --db=${OVN_NB_MASTERS} --timeout=5 get-ssl
Private key: /etc/ssl/ovn/master.key
Certificate: /etc/ssl/ovn/master.crt
CA Certificate: /etc/ssl/ovn/root_ca.crt
Bootstrap: false
```

Setting it, while it is already set, locks ...

```bash
# ovn-nbctl --db=${OVN_NB_MASTERS} --timeout=5 set-ssl /etc/ssl/ovn/master.key /etc/ssl/ovn/master.crt /etc/ssl/ovn/root_ca.crt
2018-07-18T03:41:56Z|00003|fatal_signal|WARN|terminating with signal 14 (Alarm clock)
Alarm clock
```

**Comment by blp** [comment]
Does this only happen if ovn-nbctl is talking to server over SSL?  Does the server crash and core?

**Comment by greenpau** [comment]
> Does this only happen if ovn-nbctl is talking to server over SSL? Does the server crash and core?

@blp , it happens regardless of SSL. It looks like something prevents to `set-ssl` when it is already set.

**Comment by blp** [comment]
It seems like this should be easy to reproduce, but so far I have not succeeded.

As an experiment, please add "-v" to the ovn-nbctl command line and paste the output.  I can guess where it is hanging, but I want to be sure.

Does ovsdb-server crash?  If not, does it continue to serve out other requests after this?

**Comment by greenpau** [comment]
@blp , worth mentioning: `--db=${OVN_NB_MASTERS}` is a 3 node cluster.

> Does ovsdb-server crash? If not, does it continue to serve out other requests after this?

No, it does not.

> As an experiment, please add "-v" to the ovn-nbctl command line and paste the output. I can guess where it is hanging, but I want to be sure.

Let's retry:

```
# ovn-nbctl -V
ovn-nbctl (Open vSwitch) 2.10.90
DB Schema 5.13.0

# ovn-nbctl --db=${OVN_NB_MASTERS} --timeout=5 get-ssl
Private key: /etc/ssl/ovn/myOvnMaster.key
Certificate: /etc/ssl/ovn/myOvnMaster.crt
CA Certificate: /etc/ssl/ovn/myRootCA.crt
Bootstrap: false
```

It works for me now. Perhaps, it was not working in `2.9`. Non issue then.

```
# ovn-nbctl --db=${OVN_NB_MASTERS} --timeout=5 set-ssl /etc/ssl/ovn/myOvnMaster.key /etc/ssl/ovn/myOvnMaster.crt /etc/ssl/ovn/myRootCA.crt
```
