### ISSUE TITLE
Windows: dpif-netlink interface is broken in OVS 2.10

### ISSUE THREAD

**Issue by shashankram** [openvswitch/ovs-issues#164]
In OVS 2.10,  "miss upcall" does not work. As a result there are no flows being programmed by vswitchd. This is because the dpif-netlink interface is broken for windows.

In datapath-windows/ovsext/User.c, the OvsGetQueue() function does not return the upcall queue.

        upcallQueue = OvsGetQueue(elem->upcallPid);
        if (!upcallQueue) {
            /* No upcall queue found, drop this packet. */
            InsertTailList(&dropPackets, &elem->link);
        } else {

I suspect the following commits could have caused the breakage:
https://github.com/openvswitch/ovs/commit/69c51582ff786a68fc325c1c50624715482bc460
https://github.com/openvswitch/ovs/commit/b1d98f2dd0f7f2e4131e6595279fa44aa78cfb43

**Comment by aserdean** [comment]
The breakage is cause by:
https://github.com/openvswitch/ovs/commit/69c51582ff786a68fc325c1c50624715482bc460 
where the vport socket pool on Windows is no longer used.

I sent a tentative patch here: https://patchwork.ozlabs.org/patch/996543/
Can you please give it a spin?

Thanks,
Alin.

**Comment by shashankram** [comment]
The patch looks good to me, I tested it out and it works as expected.
