### ISSUE TITLE
Selecting a bucket in group table

### ISSUE THREAD

**Issue by burhanqayoom** [openvswitch/ovs-issues#178]
I am not clearly able to understand how a bucket is selected when a new flow comes in. 
I checked these link:
https://mail.openvswitch.org/pipermail/ovs-discuss/2016-August/022282.html
http://www.openvswitch.org//support/dist-docs/ovs-ofctl.8.txt
But still things are not clear.
"   select       Execute  one  bucket  in  the group, balancing across the
                     buckets according to their weights.  To select a  bucket,
                     for  each live bucket, Open vSwitch hashes flow data with
                     the bucket ID and multiplies by the bucket weight to  ob‐
                     tain  a  ``score,''  and then selects the bucket with the
                     highest score. "
Let us say there are two buckets with bucketid 0 and 1 with weight 6 and 4 resp. When a new flow comes, the header fields are hashed with the bucketids 0 and 1 and then multiplied with 6 and 4 resp. How does this ensure that of all the flows coming to the group table, the flows are divided in the ratio of 6:4 through buckets 0 and 1. 

How a hash is made symmetric? Which hashing technique is symmetric in nature, such that the interchange of source tcp port and destination tcp port does not change the hash?

**Comment by blp** [comment]
A hash can be made symmetric by combining source and destination data in a symmetric way and then hashing the result, e.g. hash(dst ^ src).

I'll leave it to you to figure out why the scoring method works.

**Comment by burhanqayoom** [comment]
Can you please share some link how 'scoring' method works? I am not able to find anything.
