### ISSUE TITLE
OVS-DPDK: Configuring queues on runtime or after deployment

### ISSUE THREAD

**Issue by MuhammadMunir12** [openvswitch/ovs-issues#186]
I have a query about the configuration of queues length, is it possible to increase queue length on runtime or we've to stop the eth-device first then increase the queue length?
I am not asking in term of multiple queues. If i have only one queue setup, is it possible to increase its length on runtime or post deployment?

Regards,
Muhammad Munir

**Comment by igsilya** [comment]
Hi.  It's required to stop using device before reconfiguring it. Once you've changed `n_rxq_desc` or `n_txq_desc` for desired port, OVS will stop it, reconfigure it and start back.  So the port will be stopped and restarted anyway by OVS, but you don't need to do anything by hands, process is fully automated.
