### ISSUE TITLE
[Blocker]OVS Windows: ovs-vswitchd always exists with netlink msg sequence assertion failure

### ISSUE THREAD

**Issue by ruicao93** [openvswitch/ovs-issues#187]
**Description**:
ovs-vswitchd always exists with netlink msg sequnce assertion on windows.

**How to reproduce**:
- Start ovsdb-server and ovs-vswitchd
- ovs-vsctl --no-wait --may-exist add-br br-int
- Then ovs-vswitchd will exit with error:
> 2020-04-27T10:55:34.183Z|00006|util|EMER|lib/netlink-socket.c:992: assertion request_nlmsg->nlmsg_seq == reply_nlmsg->nlmsg_seq failed in nl_sock_transact_multiple__()

I tried the branch-2.13 and master, the issue can be reproduced on both of them.

**LOG**:
```
2020-04-27T10:55:34.180Z|00003|reconnect|INFO|unix:C:/openvswitch/var/run/openvswitch/db.sock: connecting...
2020-04-27T10:55:34.180Z|00004|reconnect|INFO|unix:C:/openvswitch/var/run/openvswitch/db.sock: connected
2020-04-27T10:55:34.183Z|00005|dpif_netlink|INFO|The kernel module does not support meters.
2020-04-27T10:55:34.183Z|00006|util|EMER|lib/netlink-socket.c:992: assertion request_nlmsg->nlmsg_seq == reply_nlmsg->nlmsg_seq failed in nl_sock_transact_multiple__()
```

**Root cause**:
I tried to root cause the issue. It seems the "dpif_netlink_set_features()" function misses a required field(dp name) when setting feature to kernel("dpif_netlink_dp_transact").

I verified my guess using [patch(# 319)](https://github.com/openvswitch/ovs/pull/319) and it works.

@horms @aserdean @blp : Could you help confirm if it's a bug? The issue is introduced by commit: [b2ae40690ed7925518619039c5d1e885f7d0acdf](https://github.com/openvswitch/ovs/commit/b2ae40690ed7925518619039c5d1e885f7d0acdf)

- lib/dpif-netlink.c:
```
static int
dpif_netlink_set_features(struct dpif *dpif_, uint32_t new_features)
{
......
    dpif_netlink_dp_init(&request);
    ++++ request.name = dpif_->base_name;    <<<<<<<<<<<<<<<<<<<<< request.name should be set
    request.cmd = OVS_DP_CMD_SET;
    request.dp_ifindex = dpif->dp_ifindex;
    request.user_features = dpif->user_features | new_features;

    error = dpif_netlink_dp_transact(&request, &reply, &bufp);
......
    return error;
}
```

- datapath-windows/ovsext/Datapath.c:
```
static NTSTATUS
HandleDpTransactionCommon(POVS_USER_PARAMS_CONTEXT usrParamsCtx,
                          UINT32 *replyLen)
{
   ...
    static const NL_POLICY ovsDatapathSetPolicy[] = {
        [OVS_DP_ATTR_NAME] = { .type = NL_A_STRING, .maxLen = IFNAMSIZ },      <<<<<<<<<<<<<<<<<<<<< .optional=False, so "OVS_DP_ATTR_NAME " must be a required option.
        [OVS_DP_ATTR_UPCALL_PID] = { .type = NL_A_U32, .optional = TRUE },
        [OVS_DP_ATTR_USER_FEATURES] = { .type = NL_A_U32, .optional = TRUE },
    };
   ...
}
```

**Comment by blp** [comment]
I'm not sure why the Windows and Linux datapaths behave differently here but the patch seems fine. I applied it to master and branch-2.13.
