### ISSUE TITLE
ovs-vswitchd.log ovsdb-server.log     log file size unlimited increase 

### ISSUE THREAD

**Issue by qjwu888** [openvswitch/ovs-issues#193]
Hi :
openvswitch-2.13.0

Just one question：

How to set the ovsdb-server.log and ovsdb-server.log size, if eq the size,then reopen or rewite it. 
Don't  increase great than the size.
Could anyone can help me?

**Comment by igsilya** [comment]
OVS doesn't handle log rotation.  You could configure logrotate (https://linux.die.net/man/8/logrotate) daemon that available in most linux distributions.
Configuration examples:
- https://github.com/openvswitch/ovs/blob/master/rhel/etc_logrotate.d_openvswitch
- https://github.com/openvswitch/ovs/blob/master/debian/openvswitch-switch.logrotate

For your case, you will need to use 'size' or 'maxsize' options.
