### ISSUE TITLE
Encountered compilation issue with OVS 2.13.1 in override_dh_installman step

### ISSUE THREAD

**Issue by rameshganapathi** [openvswitch/ovs-issues#194]
make[3]: Leaving directory '/build/repos/workspace/debian/stretch/x86_64/build/open-source-ovs/openvswitch-2.13.1'
   dh_installdocs
   dh_installchangelogs
   debian/rules override_dh_installman
make[3]: Entering directory '/build/repos/workspace/debian/stretch/x86_64/build/open-source-ovs/openvswitch-2.13.1'
dh_installman --language=C
utilities/ovs-appctl.8: No such file or directory at /usr/bin/dh_installman line 131.
debian/rules:97: recipe for target 'override_dh_installman' failed
make[3]: *** [override_dh_installman] Error 2
make[3]: Leaving directory '/build/repos/workspace/debian/stretch/x86_64/build/open-source-ovs/openvswitch-2.13.1'
debian/rules:25: recipe for target 'binary' failed
make[2]: *** [binary] Error 2
make[2]: Leaving directory '/build/repos/workspace/debian/stretch/x86_64/build/open-source-ovs/openvswitch-2.13.1'
make[1]: *** [/build/repos/workspace/debian/stretch/x86_64/build/open-source-ovs.built] Error 2
make[1]: Target `install-fw' not remade because of errors.
make[1]: Leaving directory `/build/repos/open-source-ovs'
make: *** [install-recursive] Error 2

**Comment by igsilya** [comment]
Thanks for the report.  It seems like we're missing at least three patches on branch-2.13:
```
* 3c18bb0fe 2020-05-14 | debian: Fix package dependencies [Roi Dayan]
* fe175ac17 2020-05-15 | debian: Add python3-sphinx to ovs build dependencies [Ansis Atteka]
* c101cd417 2020-05-13 | debian: Fix broken build after some man pages became generated from RST [Ansis Atteka]
```
These are bug fixes, but wasn't backported for some reason while applying.

@ansisatteka, could you, please, backport them?

**Comment by rameshganapathi** [comment]
Hi Ilya,

Thank you for the quick response.

Thank you,
Warm Regards,
Ramesh.G

**Comment by igsilya** [comment]
OK.  Patches are backported now:
https://mail.openvswitch.org/pipermail/ovs-dev/2020-August/374186.html
Thanks to Aaron!

Will be part of the next stable release.
