### ISSUE TITLE
/etc/openvswitch/conf.db file size unlimited increase 

### ISSUE THREAD

**Issue by qjwu888** [openvswitch/ovs-issues#203]
Hi :
My device OS is openwrt, with openvswitch-2.13.0.
The device is in SDWAN ,Often add and delete interfaces in the OVS bridge,So i meet an issue,
After long time run , conf.db file size unlimited increase,But my device flash Limited space.
How to solve this problem,Could anyone can help me?

**Comment by igsilya** [comment]
`ovsdb-server` should automatically compact the database if it grows significantly.  The check happens once in 10-20 minutes.  If for some reason it's not sufficient, you can trigger compaction manually with `ovs-appctl -t ovsdb-server ovsdb-server/compact`.

**Comment by qjwu888** [comment]
Hi igsilya:
Thanks for your reply.
