### ISSUE TITLE
Question: ovs future on Windows

### ISSUE THREAD

**Issue by fw2568** [openvswitch/ovs-issues#208]
Hello,

it looks like that cloudbase has stopped maintaining ovs for windows. Could you share some information if there are currently maintainers for the Windows implementation and if Windows will be supported also in future?

Many thanks,
Frank

**Comment by blp** [comment]
On Wed, Jun 02, 2021 at 02:20:25PM -0700, Frank Wagner wrote:
> it looks like that cloudbase has stopped maintaining ovs for
> windows. Could you share some information if there are currently
> maintainers for the Windows implementation and if Windows will be
> supported also in future?

I think it's correct that Cloudbase is no longer maintaining OVS for
Windows.  I don't think anyone has stepped up to provide support.  The
OVS maintainers would welcome it, of course.

**Comment by fw2568** [comment]
Many thanks for the quick response, Ben.

Ok, understood. We may be able to step in, but I first have to review current code for windows data path.
I will later send you a mail with my contact, so we could share details how to proceed here.

Thanks,
Frank

**Comment by aserdean** [comment]
@fw2568
I'm extremely happy to hear that!
Feel free to include me as well.
