### ISSUE TITLE
Compiling ovsext on Windows fails due to missing include header

### ISSUE THREAD

**Issue by aserdean** [openvswitch/ovs-issues#21]
Steps to reproduce:
Clone the repository (git clone https://github.com/openvswitch/ovs.git).
Go to the folder datapath-windows.
Open the solution extensions.sln in Visual Studio.
Build the solution.

The output from the compiler:
1>------ Build started: Project: ovsext (OVSExt\ovsext), Configuration: Win8.1 Release x64 ------
1> Stamping x64\Win8.1Release\ovsext.inf [Version] section with DriverVer=07/30/2014,19.44.3.258
1> precompsrc.c
1>c:\temp\30_07_2014\ovs\lib/netlink-protocol.h(32): fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory

Moved from: https://github.com/openvswitch/ovs/issues/11

**Comment by nithinrajub** [comment]
The error is slightly different after Ben's changes to auto-generate openvswitch.h as odp-netlink.h. Assigning to Ankur to take a look.

**Comment by ankursh** [comment]
The error is fixed now.
Commits:
99f368f446358d192226c385882ef75450b737ab
c640e3ce1b61eb572c3dd120a652fbfdc80758c3

As mentioned in the commit. Please build the user space before building kernel.
