### ISSUE TITLE
Possibly conflicts with libvirt qos

### ISSUE THREAD

**Issue by jshen28** [openvswitch/ovs-issues#210]
we are finding that Ovs is deleting tc ingress qdisc ffff: which is used by libvirt for rate limiting. 
No qos is set on ovs side, any idea why it is happening? thank you.

**Comment by igsilya** [comment]
Do you have HW offloading configured?  OVS may add/del qdiscs while probing/using HW offload.

**Comment by blp** [comment]
OVS tends to believe that it "owns" QoS on its ports. That makes it clear out any settings that other software puts in. We have a way to avoid that for egress qos (the `linux-noop` QoS type) but not for ingress QoS. (I think this is a desirable feature to add though.)

**Comment by jshen28** [comment]
I am not using HW offloading, it is a tap device.

**Comment by jshen28** [comment]
@igsilya it is a tap device used and all ports are connected to `br-int` which does not have any hardware interface.
