### ISSUE TITLE
AppVeyor fails building the windows kernel driver

### ISSUE THREAD

**Issue by fw2568** [openvswitch/ovs-issues#211]
> BTW, AppVeyor suddenly started to fail while building the windows kernel driver:
> https://ci.appveyor.com/project/blp/ovs/builds/39596663/job/31v0ca9xa7q0h2s7#L2919
> I suppose some part of environment changed.
> @aserdean , @fw2568 , if you can take a look that would be great.

@igsilya I'm aware of this issue as I had it on my own environment. Most probably AppVeyor has updated to VS 2019 16.10:
https://github.com/dbosoft/ovs/commit/302d3e5b6d4ad03237a4dfe38ae01edf55f288a5 

Didn't submitted this as PR as I still had hope that MS will fix this soon. I will submit it upstream later.

_Originally posted by @fw2568 in https://github.com/openvswitch/ovs-issues/issues/209#issuecomment-861420971_

**Comment by fw2568** [comment]
yes it was updated: https://www.appveyor.com/updates/2021/06/14/

**Comment by fw2568** [comment]
@aserdean better approach, thanks!

**Comment by aserdean** [comment]
Fixed with commit: https://github.com/openvswitch/ovs/commit/c16b9ac74df22e57d6ce69a3140c0fafb4a7ccf4
