### ISSUE TITLE
how to set egress qos for internal port

### ISSUE THREAD

**Issue by jshen28** [openvswitch/ovs-issues#215]
Hello,

according to [report](https://bugs.launchpad.net/neutron/+bug/1732852) looks like egress qos on internal port does not work. I can verify that using ovs 2.15.0 on ubuntu 20.04. while `ingress_policing_rate` and `ingress_policing_burst` works, setup qos and default queue with max-rate does not seem to work for vm using internal port. same qos setup does work for veth pairs. qos type is linux-htb.

what should I do to properly setup egress qos for an internal port ? thank you.

**Comment by blp** [comment]
Internal ports don't have a queue. Egress QoS requires queuing, so it's not going to work with them. You will have to find some other way to accomplish your goal.  I think that metering, for example, will work.

**Comment by jshen28** [comment]
thank you for answering.. by the way, could you please update documentation as well..

**Comment by jshen28** [comment]
Besides, I am thinking metering is not as useful as QoS because

* setup a default QoS is pretty easy and does not rely on any openflow while openflow based meter requires using openflow which is not quite easy to use for a complex env
* I do not know to use meter for egress traffic, now right I am thinking using dest mac address but mac address could be changed...

**Comment by jshen28** [comment]
By the way, is QoS working for tap devices?

**Comment by blp** [comment]
Feel free to submit a PR for documentation.
