### ISSUE TITLE
[Windows] Packet not new is mistakenly considered ct_state: +new 

### ISSUE THREAD

**Issue by lzhecheng** [openvswitch/ovs-issues#232]
In project Antrea, a flow is installed: table=105, `table=ConntrackCommit, priority=200,ct_state=+new+trk,ip,reg0=0x1/0xf actions=ct(commit,table=HairpinSNAT,zone=65520,exec(load:0x20->NXM_NX_CT_MARK[]))`. It has match condition: `+new` but it is found that a not new request packet hit this flow unexpectedly. It should be a syn ack not syn.

The behavior is that a Pod curl www.google.com. The pipeline design is that a container sends a request packet into OVS pipeline via the container port and leaves OVS via a port called antrea-gw0. The reply packet will enter OVS via antrea-gw0 and it shouldn't hit the flow above.

The investigation is that: the reply packet has incorrect dl_dst and it is modified in this flow:
`table=L3Forwarding, priority=210,ct_state=+rpl+trk,ct_mark=0x20,ip actions=mod_dl_dst:00:15:5d:1a:d4:02,resubmit(,L2Forwarding)`
And the reason why reply packet meets the match condition: ct_mark=0x20 is the first flow shown above.

Wireshark results:
container port:
![image](https://user-images.githubusercontent.com/15087620/140268914-6aed8ceb-e660-49a1-bc26-70b3cef69585.png)

antrea-gw0 port:
![image (1)](https://user-images.githubusercontent.com/15087620/140268927-117303de-6a07-45c6-98a8-1196fddbd053.png)

[wirshark_results.zip](https://github.com/openvswitch/ovs-issues/files/7472773/wirshark_results.zip)

**Comment by tnqn** [comment]
We found the issue happened when ip fragments were received on one OVS port and there is an action ct in the pipeline. The fragments will be reassembled before sending to connection tracker according to the doc (https://man7.org/linux/man-pages/man7/ovs-actions.7.html):

       If ct is executed on IPv4 (or IPv6) fragments, then the message
       is implicitly reassembled before sending to the connection
       tracker and refragmented upon output, to the original maximum
       received fragment size. Reassembly occurs within the context of
       the zone, meaning that IP fragments in different zones are not
       assembled together. Pipeline processing for the initial fragments
       is halted. When the final fragment is received, the message is
       assembled and pipeline processing continues for that flow. Packet
       ordering is not guaranteed by IP protocols, so it is not possible
       to determine which IP fragment will cause message reassembly (and
       therefore continue pipeline processing). As such, it is strongly
       recommended that multiple flows should not execute ct to
       reassemble fragments from the same IP message.
However, the flow key of the reassembled packet was not updated with the correct 5-tuple, and was still the ones set in the last fragment that triggers the assembly, which are empty values. Then it failed to get the existing conntrack entry when looking up CT and the packets was considered "new". I confirmed Linux datapath doesn't have this issue as it regenerates the L4 header for the flow key from the reassembled packet:
https://github.com/openvswitch/ovs/blob/1bdda7b6d53c92e877b457157676aff326414c53/datapath/conntrack.c#L596-L599

**Comment by aserdean** [comment]
Fixed with commit:
https://github.com/openvswitch/ovs/commit/71eb2ec446b4f25eec2360f65e018162c072973c
