### ISSUE TITLE
[Windows] Loading data to NXM_OF_IP_TOS doesn't take effect

### ISSUE THREAD

**Issue by gran-vmv** [openvswitch/ovs-issues#244]
On Windows platform, we cannot load DSCP value to `NXM_OF_IP_TOS` for an IP/IPv6 packet

OVS version: 2.15.2
OS: Microsoft Windows Server 2019 Standard

Reproduce:
1. Setup OVS bridge with multiple ports
2. Add a flow to load a non-zero DSCP value to NXM_OF_IP_TOS for test packet
3. Send zero DSCP test packet to one OVS port, the packet should hit above flow
4. After test packet output to another OVS port, the DSCP is zero.

Using `PacketOut` with load action instead of step 2/3 can also reproduce this issue.
`output`, `ct` action to a packet will lose the `loaded DSCP`.
Packet original DSCP value won't be affected by this issue.

**Comment by aserdean** [comment]
Fixed with commit: https://github.com/ovsrobot/ovs/commit/c24b5c73e22f8203139a137eba135388dcb911f6
