### ISSUE TITLE
Is ovs-vsctl client backwards compatible with previous ovs-vswitchd?

### ISSUE THREAD

**Issue by jshen28** [openvswitch/ovs-issues#246]
Hello,

  I would like to ask if ovs-vsctl compatible with an older  ovs-vswitchd? Thank you.

**Comment by junka** [comment]
ovs-vsctl is ovsdb cli tool, it has no compatible issue with ovs-vswitchd.
But on the other hand, some options could be added for ovsdb in some early versions.
If you want put a ovs-vsctl in a docker and mirror the db unix socket into the docker. Basic db operation for the schema tables would be good as far as I can see.

**Comment by jshen28** [comment]
thank you for clarification.
