### ISSUE TITLE
ovs-vsctl compatibility matrix

### ISSUE THREAD

**Issue by jshen28** [openvswitch/ovs-issues#258]
Hello community,

  I am looking for a matrix describing compatibility between different versions of `ovs-vswitchd` daemon and `ovs-vsctl` tool. Our use case is to access `ovs-vswitchd` service on host from a container, and the host daemon is not cotainterized yet. Is this setup problematic and is there any link to the issues? Thank you very much for help.

Best,
Jiatong Shen

**Comment by blp** [comment]
It's not something we test. The goal is for interoperability between versions. This should ordinarily come down to:
* When ovs-vsctl is older than ovs-vswitchd, it should work but it won't be able to work with tables or columns added after the ovs-vsctl version.
* When ovs-vsctl is newer than ovs-vswitchd, it should work but attempts to configure anything based on tables or columns that are missing will fail.

(The real question is the database schema version, not the ovs-vswitchd version, but ordinarily one would keep ovs-vswitchd and its database in sync.)

**Comment by jshen28** [comment]
Thank you for reply. Will `ovs-ofctl` be compatible with old `ovs-vswitchd`?

**Comment by blp** [comment]
Yes
