### ISSUE TITLE
openvswitch loading issues

### ISSUE THREAD

**Issue by chenglonglinux** [openvswitch/ovs-issues#274]
Hello Openvswitch,

I would like to share the server version I have installed, which is ovs-vswitchd 2.17.3 and DPDK 21.11.2. However, I am currently facing an issue where the ovs-vswitchd.log file always shows 96% CPU usage.

I have used the command "ovs-appctl dpif-netdev/pmd-rxq-show" to check if the offload is utilizing all four cores, but it appears that it is not fully utilizing them. Is this normal?

Additionally, the log file shows that 36789 log messages were dropped in the last 6 seconds due to excessive rate, with the latest wakeup event due to [POLLIN] on fd 2459 (AF_PACKET(ex-tap-VDXSzPMn)(protocol=0x3)<->) at lib/netdev-linux.c:1542.

The pmd thread details are as follows:

numa_id 0 core_id 2:
isolated: false
port: dpdk, queue-id: 3 (enabled), pmd usage: 15%, overhead: 2%
numa_id 0 core_id 4:
isolated: false
port: dpdk, queue-id: 1 (enabled), pmd usage: 15%, overhead: 2%
numa_id 0 core_id 6:
isolated: false
port: dpdk, queue-id: 2 (enabled), pmd usage: 18%, overhead: 2%
numa_id 0 core_id 8:
isolated: false
port: dpdk, queue-id: 0 (enabled), pmd usage: 53%, overhead: 1%
Thank you for your assistance.

**Comment by igsilya** [comment]
It looks like you're trying to send traffic between kernel and dpdk ports.  Kernel ports are handled by the main thread in OVS and they are not very performant.  If you want a good performance, you need to switch from kernel interfaces to dpdk ones.

Based on the other issue you opened, I'd guess you have kernel tap interfaces for VM connection.  You need to change them to vhost-user ports to achieve a good performance in userpsace datapath.

**Comment by igsilya** [comment]
See the following doc for configuration details: https://docs.openvswitch.org/en/latest/topics/dpdk/vhost-user/

**Comment by chenglonglinux** [comment]
I'm extremely grateful, it's very clear
i closed the issues now
