### ISSUE TITLE
How does OVS work without promiscuous mode?

### ISSUE THREAD

**Issue by cuttingedge1109** [openvswitch/ovs-issues#275]
Hi guys.
I've been running Openstack clouds with the openvswitch mechanism driver for the past few years.
Last week I had to provision an openstack environment in VMWare for development purposes and I was experiencing some networking issues like not being able to connect to the VM via the ovs external bridge from the host network.
After a bit of digging, I was able to get it to work by enabling promiscuous mode on the vmware port group. And I think I need to enable this promiscuous mode so that the bridge can receive the packets and forward them to the VMs in the hypervisor.
But I haven't used this promiscuous mod in a physical environment in years.
I wonder if this mod is automatically configured by the ovs install?
Please clarify this.
thank you.

**Comment by apconole** [comment]
OVS will automatically enable promisc on network interfaces.
