### ISSUE TITLE
[Window] BSOD happens because OVSext driver

### ISSUE THREAD

**Issue by wenyingd** [openvswitch/ovs-issues#279]
Hi,

We recently hit BSOD many times on a Windows host running OVS, and the stop code is "KMODE EXCEPTION NOT HANDLED" with failure in "OVSExt.sys".
![image (2)](https://user-images.githubusercontent.com/5153872/232727459-246e490c-dc09-4cc7-8fa5-5a5f769bf22d.png)

**Comment by aserdean** [comment]
Hey,

To help triage the bug faster, can you please share the minidump or kernel dump?

I can send you instructions on how to enable them if your system doesn’t generate them by default.

**Comment by wenyingd** [comment]
Having some troubleshooting, we find that the BSoD looks related with deletion of the Windows route. 
An example is like this,

There are three threads  running on the Windows host: 1) T0 maintains a long TCP connection with destination `10.96.0.1:443`, 2) T1 works to add routes `destination=10.96.0.1, nexthop=169.254.0.253` and `destination=169.254.0.253/32, nexthop=192.168.3.1`, `192.168.3.1` is configured on a local network adapter, 3) T2 works to delete the above two routes. T2 and T3 continue working in a interval

OVS has OpenFlow entries to perform DNAT from 10.96.0.1 to dst IP 1.1.1.2.

We observed that several acknowledge packets ( the packets are workload packets not used in handshake stage ) were not sent out from the windows host when the BSoD happened, and the listed route entries were not existing at that time.
