### ISSUE TITLE
OVS 3.1.2 ./configure rundir broken

### ISSUE THREAD

**Issue by NickDcn** [openvswitch/ovs-issues#285]
Attempting to use ./configure --with-rundir=/var/run/xxx does not work.
The same command with OVS 2.17.7 works as expected.

**Comment by igsilya** [comment]
Please, elaborate on what `does not work` mean.  On a quick check seems to work just fine.

**Comment by NickDcn** [comment]
Ok, so I didn't realize but when building Debian packages, the --with-rundir option is ignored, is this expected behaviour ?


- Steps v3.1.2:

```
./configure --with-rundir=/var/run/hostovs
make debian
make debian-deb
dpkg -i  xxx...
```

PID files are at /var/run/openvswitch

```
journalctl -xeu ovsdb-server.service
01aosc ovsdb-server[3265340]: ovs-ctl: /var/run/openvswitch/ovsdb-server.pid: pidfile check failed (No such process), aborting
```
 
(No such process because I have another instance of openvswitch configured by Kolla-Ansible)


- Using 2.17.7:

```
./configure --with-rundir=/var/run/hostovs
fakeroot debian/rules binary 
```
PID files again land at /var/run/openvswitch


- General Install 2.17.7:

```
./configure --with-rundir=/var/run/hostovs
make
make install  
```
PID files end up /var/run/hostovs

**Comment by igsilya** [comment]
> Ok, so I didn't realize but when building Debian packages, the --with-rundir option is ignored, is this expected behaviour ?

Yes.  You may notice that when  you build a debian package, OVS is getting re-configured with the options defined in `debian/rules`.  So, any options provided to the `./configure` beforehand will not have effect, unless explicitly documented.
You should be able to specify extra options via `EXTRA_CONFIGURE_OPTS` environment variable.
