### ISSUE TITLE
OVS 2.17.7 make debian not functional

### ISSUE THREAD

**Issue by NickDcn** [openvswitch/ovs-issues#286]
When attempting to run make debian with ovs version 2.17.7, make returns nothing to do for debian.

**Comment by igsilya** [comment]
`debian` is a directory.  `make debian` is asking make to produce a `debian` file/directory.  So, there is indeed nothing to do.

If you're looking for how to build debian packages, follow the documentation: https://github.com/openvswitch/ovs/blob/v2.17.7/Documentation/intro/install/debian.rst

Note that the debian packaging changed significantly in OVS 3.0, so instructions will be different for newer versions.
