### ISSUE TITLE
ovs  and ovn restart 

### ISSUE THREAD

**Issue by zhaiyj** [openvswitch/ovs-issues#300]
![image](https://github.com/openvswitch/ovs-issues/assets/17920880/cfa6ed39-a993-4dcd-a96c-0d24d40225c2)

![image](https://github.com/openvswitch/ovs-issues/assets/17920880/38df54f8-187c-4a3e-9144-dd5296cb7ef2)
![image](https://github.com/openvswitch/ovs-issues/assets/17920880/28ef7dc6-84dc-4614-bd4b-e464f4da986f)

It means use that the ovs-appctl exit or ovn-appctl exit command ？

**Comment by igsilya** [comment]
I'm not sure what you mean, but someone or something indeed called `ovn-appctl exit --restart`.

**Comment by zhaiyj** [comment]
I know why, thanks， Failed detection led to an elegant reboot
