### ISSUE TITLE
how to build openvswitch kernel moudle

### ISSUE THREAD

**Issue by bettswang** [openvswitch/ovs-issues#302]
Hi, maintainers

It seems that there is  no way to build openvswitch kernel moudle with './configure --with' on the current version. I remember this is available on the old version before v2.17. Is there some way to build the openvswitch kernel moudle on current version.  I just want to see the difference with the kernel ships as part of the upstream Linux kernel.

**Comment by igsilya** [comment]
The version in upstream Linux kernel is the only supported version.  Our copy f the module was removed in release 3.0.  The last available version is 2.17, but it is deprecated and I'd advise against using it, because it didn't receive any fixes for a long time.
