### ISSUE TITLE
Does OvS support OpenFlow‘s “OXM_OF_IPV6_EXTHDR” match field ？

### ISSUE THREAD

**Issue by plushao666** [openvswitch/ovs-issues#308]
There is a problem bothering me, just like the title says: "Can I add a flow entry matched by IPV6_EXTHDR ? " 
The following is the **ipv6_exthdr** field defined in the official OpenFlow documentation:
![image](https://github.com/openvswitch/ovs-issues/assets/73576561/adbde753-1aeb-4b73-b64b-727935161749)
But I have tried to use command line "**ovs-ofctl** add-flow s1 ipv6,ipv6_exthdr=32,actions=output:2", and the result is
**"ovs-ofctl: unknown keyword ipv6_exthdr"**.(The ovs version is 3.2.90 latest!)
I also tried to use Ryu controller to add flow entry, and Ryu returns an error message like:
```
EventOFPErrorMsg received.
version=0x4, msg_type=0x1, msg_len=0x64, xid=0xd8c053bf
 `-- msg_type: OFPT_ERROR(1)
OFPErrorMsg(type=0x4, code=0x6, data=...)
 |-- type: OFPET_BAD_MATCH(4)
 |-- code: OFPBMC_BAD_FIELD(6)
 `-- data: version=0x4, msg_type=0xe, msg_len=0x58, xid=0xd8c053bf
     `-- msg_type: OFPT_FLOW_MOD(14)
```
So is there any professional who can answer my question? Thanks very much!

**Comment by igsilya** [comment]
Hi @plushao666 .  OVS doesn't have support for this extension today.

**Comment by plushao666** [comment]
> Hi @plushao666 . OVS doesn't have support for this extension today.

Thank you! 🤞
