### ISSUE TITLE
Make GET_PID a separate ioctl or remove dependency on odp-netlink.h

### ISSUE THREAD

**Issue by nithinrajub** [openvswitch/ovs-issues#31]
> On Aug 18, 2014, at 5:08 PM, Alin Serdean aserdean@cloudbasesolutions.com
>  wrote:
> Hi Nithin,
> Just a few thoughts:
> Since get PID is a special case would it not be better to treat it as a DeviceIoControl;dwIoControlCode like OVS_IOCTL_TRANSACT (i.e. OVS_IOCTL_GET_PID)? 
> 
>  We can drop the extra headers and the whole Netlink message building/parsing since the goal is just to get a number.

hi Alin,
Thanks for taking a look.

I want to keep the message exchange to be in netlink format. Though, the possibility of changing the format of the get_pid message is very remote, I want to stick with netlink.

As regards to including header files, I do need odp-netlink-ext.h for the definition of the ioctl. odp-netlink.h was needed for ovs_header, since there is an assumption that each message is at least (nl header + genlheader + ovs_header). I can get rid of the usage of ovs_header and remove the dependency on odp-netlink.h. This will involve some kernel changes too since there's a length check there.

I wand to postpone this task for this future since the commands are evolving. I'll keep a note of it in an issue.

**Comment by svinturis** [comment]
This issue was addressed in the above mentioned patch. Closing it.
