### ISSUE TITLE
OVS website links are broken

### ISSUE THREAD

**Issue by antoninbas** [openvswitch/ovs-issues#310]
Links to the OVS documentation seem to have broken overnight.
For example, the following links used to work (until yesterday):
- https://docs.openvswitch.org/en/latest/intro/install
- https://docs.openvswitch.org/en/latest/faq/releases/

Trying to access these links now will give a 404.

The new equivalent links:
- https://docs.openvswitch.org/en/latest/intro/install/index.html
- https://docs.openvswitch.org/en/latest/faq/releases.html

I'm opening this issue to check if the change was intentional, and if not, to check if there is a plan to revert it.

cc @igsilya as it may have been caused by https://github.com/openvswitch/ovs/commit/e388bd73b70d8f053f26b609ee939d6af7d1a10c given the timeline

**Comment by igsilya** [comment]
Hi, @antoninbas.  I know about the issue.   David Marchand also reported it yesterday. I think, I can fix it by switching to a dirhtml builder in sphinx.  Let me try that.

**Comment by igsilya** [comment]
@antoninbas I posted a patch that fixes the problem for review: https://patchwork.ozlabs.org/project/openvswitch/patch/20231026175507.574054-1-i.maximets@ovn.org/

**Comment by igsilya** [comment]
@antoninbas the fix is merged and the links should work again now.  Could you, please, re-check on your side?

**Comment by antoninbas** [comment]
Thanks, it's all back to normal
