### ISSUE TITLE
Avoid calling OvsCreateAndAddPackets() if there's no queue setup

### ISSUE THREAD

**Issue by nithinrajub** [openvswitch/ovs-issues#32]
In the current code, we call into OvsCreateAndAddPackets() whenever there's a missed packet. OvsCreateAndAddPackets() allocates memory and copies the packet even if there's no packet queue setup from userspace. OvsQueuePackets() checks if there's a queue or not and drops the packet.

If we can, we should avoid allocating memory in OvsCreateAndAddPackets().

Though this is not a big deal, it can avoid churn in memory when the whole operation is a no-op.

**Comment by aserdean** [comment]
Fixed with patch https://github.com/openvswitch/ovs/commit/5019855cad0b965e32fc2342773c0915c54329bb.

Thanks @svinturis
