### ISSUE TITLE
The mac_learning_moved  indicator is very high, ovs High CPU utilization.

### ISSUE THREAD

**Issue by zhaiyj** [openvswitch/ovs-issues#332]
![Uploading 图片1.png…]()

**Comment by zhaiyj** [comment]
![Uploading 图片1.png…]()

**Comment by chaudron** [comment]
Based on the subject line (as the linked picture is not working), this means you have a MAC address rapidly moving from one port to another. You need to figure out which MAC address this is. You might be able to dump the fdb table multiple times and hopefully see the MAC address. There is no log message for this to be enabled.

**Comment by zhaiyj** [comment]
why picture is not working 
![Uploading 图片1.png…]()

**Comment by zhaiyj** [comment]
![图片1](https://github.com/openvswitch/ovs-issues/assets/17920880/69d7d926-f6ea-4482-b79d-a0d107574ea9)
br-public-net bridge move mac port high. mac is 0:00:00:13:14:a1 move port 3 to 4 or 4 to 3 , but nof found this mac.

**Comment by zhaiyj** [comment]
![企业微信截图_17169640423519](https://github.com/openvswitch/ovs-issues/assets/17920880/ffcd3c64-fd2b-4007-aa47-2c56ad955ed6)
br-public-net port mac move port high, mac is 0:00:00:13:14:a1 , but con not find this mac address.

**Comment by zhaiyj** [comment]
![image](https://github.com/openvswitch/ovs-issues/assets/17920880/7137e9d7-7f23-42f0-9ff3-434377338b19)

**Comment by chaudron** [comment]
Guess you need to figure out who on ports 3 and 4 is generating/using this MAC address, as this seems to be moving around. If it's attached to a remote switch, you need to figure out why it is switching ports this mac to different ports. This does not look like an OVS problem.

**Comment by zhaiyj** [comment]
thanks, problem solved
