### ISSUE TITLE
Build OVS from source statically

### ISSUE THREAD

**Issue by ShrirAm-cse** [openvswitch/ovs-issues#339]
Hi,

I am trying to build openvswitch version 3.3.0 statically from source from alpine & musl. The static compilation results in dynamically linked ovs binaries. 

I have followed the step of installation from the [OVS webpage](https://docs.openvswitch.org/en/latest/intro/install/general/). 
The installation procedure says that while 'configure'ing OVS `--enable-static` flag is the default.  

> By default, static libraries are built and linked against.

![Screenshot from 2024-08-30 14-42-41](https://github.com/user-attachments/assets/d2132bd0-1c20-4ca1-9224-5b4033300854)

### Steps to reproduce

- Start an alpine:3.20 docker container 
- Install the necessary dependencies
- Download [OVS 3.3.0 release](https://github.com/openvswitch/ovs/archive/refs/tags/v3.3.0.tar.gz)
- Follow installation steps
```
./boot.sh
./configure
make
make install
# To find the link type run the following command 
file ovs-vsctl
```
---

In addition to this, I have also tried the following -

- Tried setting `--enable-static` option on configure and added `-g -O2 -static` c flags to build statically.
- Openvswitch installed by `apk add openvswitch` also resulted in dynamically linked binary.
- Cross compiling ovs from Ubuntu gnu also resulted in dynamically linked binary.
- Other versions of OVS also found to have generated dynamically linked binary.

---

### How to build OVS from source statically?

**Comment by igsilya** [comment]
`--enable-static` is only responsible for OVSes own libraies, i.e. it controls if `libofproto.so` and `libopenvswitch.so`, etc. will be generated or will be statically linked into every OVS binary.  It doesn't affect linking with external libraries, which are dynamic by default.

I managed to build fully static binaries with:
```
./configure --enable-static --disable-shared LDFLAGS='--static' --disable-ssl
```
I had to disable SSL since I don't have static libs for OpenSSL and was also uisng glibc, which doesn't like being staticly linked, so your mileage may vary.  However, the result is:
```
# file ./utilities/ovs-vsctl
./utilities/ovs-vsctl: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=5f2a3a722221aa477e7a88bc132d73d4145f2f63, for GNU/Linux 3.2.0, with debug_info, not stripped, too many notes (256)
# ldd ./utilities/ovs-vsctl
        not a dynamic executable
# ./utilities/ovs-vsctl --version
ovs-vsctl (Open vSwitch) 3.4.90
DB Schema 8.7.0
```

**Comment by ShrirAm-cse** [comment]
Thank You.

Adding `LDFLAGS='--static'` built static binaries.
