### ISSUE TITLE
Create an installer for OVS on Hyper-V

### ISSUE THREAD

**Issue by nithinrajub** [openvswitch/ovs-issues#34]
Logging an issue so this is on the radar/

**Comment by svinturis** [comment]
The installer should contain the following rows, with its associated values, in its MSI tables:

```
Description = Open vSwitch forwarding switch extension
DriverID = {583CC151-73EC-4A6A-8B47-578297AD7623}
DriverInstallParams = /q
DriverVersion = 1.0
ExtensionType = Forwarding
Manufacturer = Open vSwitch
MinApplicableOSVersion = 6.2
ProductName = Open vSwitch Extension
```

The above values, like Description, DriverID, DriverVersion, Manufacturer, ProductName should match the corresponding strings from the install file.

**Comment by aserdean** [comment]
Commit: https://github.com/openvswitch/ovs/commit/d183efc22b2b0b84c341500a73f567f98f4d00f4.
