### ISSUE TITLE
Get service-model from a live instance of OVSDB and health checking

### ISSUE THREAD

**Issue by legitYosal** [openvswitch/ovs-issues#347]
I think we need a live endpoint in OVSDB to show "service-model" of the current instance, is there anything already on ovsdb-client or ovs-appctl?

I am facing two issues here:

1. When you initialize relays in your cluster, You can monitor number of live relay instances almost like this:
```
number of (ovsdbs which are healthy && are on the target hosts I have installed relays)
```
As we have no metric on a initialized OVSDB instances to find out it is relay or OVSDB southbound itself, we can even expand it to where we have multiple OVN deployments, which are having relays, which can not be separated from each other, usually we have these metrics:
```
ovn_up{host="", ip="", instance="nb or sb"}
```
So if we have an API from OVSDB to show what is the service model it will be great:
```
ovn_up{host="", ip="", instance="nb or sb", service-model="" or is_relay=""}
```

2. Currently we are health checking OVSDB with these methods:
* OVSDB port is opened
* ovsdb-client list-tables is working or not(or similar to that)

So when you want to health check if your relay server is up, you can do:
```
ovsdb-client list-tables | grep -q Connection && ss -lnp | grep -q 16642 && echo $?
```
Which is not very beautiful, I would like to know what is the best method to check relay OVSDBs health, and also is there any option on getting OVSDB service-model and health status from cli?

@igsilya

**Comment by legitYosal** [comment]
I noticed I can find out about database by executing these queries: 
```
ovsdb-client query unix:/run/openvswitch/db.sock "[\"_Server\",{\"table\":\"Database\",\"where\":[],\"op\":\"select\",\"columns\":[\"_uuid\",\"connected\",\"leader\",\"model\",\"name\"]}]"
```
Which shows what service model is the database:
```
[{"rows":[{"_uuid":["uuid","3a03bcf8-b180-41d3-9c21-c6079bd94152"],"connected":true,"leader":false,"model":"relay","name":"OVN_Southbound"},{"_uuid":["uuid","606e4442-5411-4f63-adf1-09ea9621b72e"],"connected":true,"leader":true,"model":"standalone","name":"_Server"}]}]
```

**Comment by igsilya** [comment]
Thanks for sharing the solution!  Yes, the `_Server` database is served by every ovsdb-server process and can be used to get information about other databases on this server including their service model, schema and so on.
