### ISSUE TITLE
downsides of increasing Raft election timeout

### ISSUE THREAD

**Issue by legitYosal** [openvswitch/ovs-issues#348]
Hi,
On a loaded cluster, with 100K acls and 200K logical flows, my cluster will go crazy, some times having no leader at all:
<img width="1434" alt="image" src="https://github.com/user-attachments/assets/4505c64a-db02-4c41-a530-14544c46b256">

And when increasing the timeout to for example 10 seconds it will be more stable:
<img width="1434" alt="image" src="https://github.com/user-attachments/assets/356a13e1-25cb-4301-b767-727e1880c791">

I guess if I really loose the leader it will get a complete 10+ seconds down time, which is acceptable, I am asking other than this, may it affect any thing else? for example can it cause chassis to be synced with delay? 

currently using ovs 3.3.2

**Comment by igsilya** [comment]
Increase of the election timer should not affect normal operation, only the reaction time when you actually loose the leader for one reason or another.
FWIW, high-scale clusters usually run with higher election timers on southbound database, at least.  10 seconds should be fine in most cases.

You may check the logs and look for messages from the `cooperative_multitasking` module and see what are the overrun values for for the small election timer.

**Comment by legitYosal** [comment]
Thanks a lot
