### ISSUE TITLE
Implement a Get-VMNetworkAdapterWithOvsPort

### ISSUE THREAD

**Issue by nithinrajub** [openvswitch/ovs-issues#51]
There's no easy way to figure out if there's a friendly name set for a VIF or not. The only way I know is to set a breakpoint in the kernel during VIF attach and look at the portParams or nicParams.

It would be useful if we had a Get-VMNetworkAdapterWithOvsPort <VM Name>
The output could be very similar to inbuilt Get-VMNetworkAdapter with the OVS name also being shown in addition.

I'm assigning this to Alin, but lease feel free to assign it to someone else or bounce it back if you guys cannot work on it.

**Comment by aserdean** [comment]
Think the function is already implemented under the name:
Get-VMNetworkAdapterByOVSPort
Is this the functionality that you wanted?

**Comment by nithinrajub** [comment]
I want to provide as input name rather than ovs port name.

Thanks,
-- Nithin
- sent from mobile -

On Nov 3, 2014, at 11:39, "Alin Gabriel Serdean" <notifications@github.com<mailto:notifications@github.com>> wrote:

Think the function is already implemented under the name:
Get-VMNetworkAdapterByOVSPort
Is this the functionality that you wanted?

##

**Comment by aserdean** [comment]
Closed with commit:
https://github.com/openvswitch/ovs/commit/a22a9529fb86aa906a6a4e1f014826380f4e81d0
