### ISSUE TITLE
Account for hybrid networking in the OVS Hyper-V switch Extension

### ISSUE THREAD

**Issue by nithinrajub** [openvswitch/ovs-issues#52]
In Windows 2012 R2 (as opposed to Windows 2012), Microsoft has introduced a feature called Hybrid Networking [1]. The reasoning seems to be to provide clarity to switch forwarding extensions (such as OVS-EXT) on how to handle packets that must ideally be handled by Microsoft Network Virtualization layer. The code change itself is not big. We just need to check for 'fwdDetail->NativeForwardingRequired' in an NBL, and let NDIS process the packet instead of OVS mucking with it. For code reference, please take a look at the MsForwardExt.c forwarding sample driver provided with WDK 8.1. Of course, it would be the prerogative of whoever works on this issue to do more research to figure out if anything more needs to be done.

Just logging an issue here. Anyone can pick it up.

1 - "http://msdn.microsoft.com/en-us/library/windows/hardware/dn653325(v=vs.85).aspx"

**Comment by svinturis** [comment]
As Nithin pointed out, we must split the incoming traffic into NVGRE and non-NVGRE packets. All non-NVGRE traffic is forwarded by the OVS extension and processed as usual, and the NVGRE traffic is passed to NDIS to be handled by the HNV module.

**Comment by svinturis** [comment]
Currently the OVS extension supports NDIS 6.30. Hybrid forwarding involves supporting NDIS 6.40.

**Comment by svinturis** [comment]
NDIS 6.40 is substantially the same as NDIS 6.30.

In addition to an NDIS 6.30 driver, an NDIS 6.40 driver must be compliant with the following requirements:
1. It must report the correct NDIS version when it registers with NDIS;
   The `NDIS_FILTER_DRIVER_CHARACTERISTICS` structure must have `MajorNdisVersion` and `MinorNdisVersion` members correctly set. This requires adding NDIS640=1 compiler settings. No other code change is necessary.
2. It must use the NDIS 6.40 versions of data structures.
   The following structures and enumerations were updated for NDIS 6.40:

``` C++
typedef union _NDIS_SWITCH_FORWARDING_DETAIL_NET_BUFFER_LIST_INFO {
  UINT64 AsUINT64;
  struct {
    UINT32 NumAvailableDestinations  :16;
    UINT32 SourcePortId  :16;
    UINT32 SourceNicIndex  :8;
#if (NDIS_SUPPORT_NDIS640)
    UINT32 NativeForwardingRequired  :1;
    UINT32 Reserved1  :1;
#else 
    UINT32 Reserved1  :2;
#endif 
    UINT32 IsPacketDataSafe  :1;
    UINT32 SafePacketDataSize  :12;
    UINT32 Reserved2  :9;
  };
} NDIS_SWITCH_FORWARDING_DETAIL_NET_BUFFER_LIST_INFO, *PNDIS_SWITCH_FORWARDING_DETAIL_NET_BUFFER_LIST_INFO;

typedef enum _NDIS_SWITCH_PORT_PROPERTY_TYPE { 
  NdisSwitchPortPropertyTypeUndefined,
  NdisSwitchPortPropertyTypeCustom,
  NdisSwitchPortPropertyTypeSecurity,
  NdisSwitchPortPropertyTypeVlan,
  NdisSwitchPortPropertyTypeProfile,
  NdisSwitchPortPropertyTypeIsolation,     /* supported in NDIS 6.40 and later */
  NdisSwitchPortPropertyTypeRoutingDomain, /* supported in NDIS 6.40 and later */
  NdisSwitchPortPropertyTypeMaximum
} NDIS_SWITCH_PORT_PROPERTY_TYPE, *PNDIS_SWITCH_PORT_PROPERTY_TYPE;
```

The `NdisSwitchPortPropertyTypeIsolation` enumeration value specifies an isolation port property defined using the `NDIS_SWITCH_PORT_PROPERTY_ISOLATION` structure.

``` C
typedef struct _NDIS_SWITCH_PORT_PROPERTY_ISOLATION {
  NDIS_OBJECT_HEADER  Header;
  ULONG               Flags;
  NDIS_ISOLATION_MODE IsolationMode;
  BOOLEAN             AllowUntaggedTraffic;
  UINT32              DefaultIsolationId;
} NDIS_SWITCH_PORT_PROPERTY_ISOLATION, *PNDIS_SWITCH_PORT_PROPERTY_ISOLATION;
```

The `NdisSwitchPortPropertyTypeRoutingDomain` enumeration value specifies a routing domain port property defined using the `NDIS_SWITCH_PORT_PROPERTY_ROUTING_DOMAIN` structure.

``` C
typedef struct _NDIS_SWITCH_PORT_PROPERTY_ROUTING_DOMAIN {
  NDIS_OBJECT_HEADER       Header;
  ULONG                    Flags;
  NDIS_ROUTING_DOMAIN_ID   RoutingDomainId;
  NDIS_ROUTING_DOMAIN_NAME RoutingDomainName;
  ULONG {
    USHORT FirstIsolationEntryOffset;
  }                   NumIsolationEntries;
} NDIS_SWITCH_PORT_PROPERTY_ROUTING_DOMAIN, *PNDIS_SWITCH_PORT_PROPERTY_ROUTING_DOMAIN;
```

**Comment by nithinrajub** [comment]
Sorin, thanks for doing the research.

**Comment by EitanEliahu** [comment]
Sorin, I just want to clarify that since we register with NDIS as a 6.30 filter driver there is no requirement to take any action or change.  6.30 driver works in > 6.40 wrapper.

#define NDIS_FILTER_MAJOR_VERSION 6
#define NDIS_FILTER_MINOR_VERSION 30
    driverChars.MajorNdisVersion = NDIS_FILTER_MAJOR_VERSION;
    driverChars.MinorNdisVersion = NDIS_FILTER_MINOR_VERSION;

**Comment by nithinrajub** [comment]
Eitan,
Are you implying that we should not register as a 6.40 driver at all? I think having conditional code, and handling the 6.40 case is a good thing. We may not be implementing any code specifically for 6.40, but handling the cases as required by 6.40 is a good thing I think. We'll be fully compliant with 6.40 rather than be working in "backwards compatibility" mode.

What do you think?

**Comment by EitanEliahu** [comment]
I think we need to look from a wider perspective. Obviously, just to filter out NVGRE packets is not a compelling reason as the wrapper does it for the driver if registered with < 6.40. I think we cannot just support 6.40 as the driver needs to run on Windows 2012.
If we decide that it worth the transition we need to support both drivers (using the MACRO you suggested). This means another Solution configuration, install script which supports both and certification and QA which support both drivers.
Sounds like a significant maintenance effort but we will not be able to avoid in the future.
I suggest that we will keep this issue open for now and look into it once we identify more compelling reasons to support upgrading.

**Comment by nithinrajub** [comment]
Thanks for listing out the "pending work" to call OVS 6.40 complaint. I agree with the points.

Based on the research that Sorin has done, code-wise, it may not be lot of changes. IMO, we should make the code changes and keep it conditional using the MACRO. We can decide to nuke these changes if there's significant effort required later in terms of maintanance later on. As I see it, driver certification is not happening anytime soon.

Is this a reasonable way to close this issue?

**Comment by svinturis** [comment]
Guys, NDIS 6.40 includes all NDIS 6.30, plus the additional things I have pointed above and that's it. None of which are affecting the OVS extension, code-wise. So we don't need to do anything special to make OVS to be NDIS 6.40 compliant, other than correctly register it to NDIS. In this way we can make use of the enhanced `NDIS_SWITCH_FORWARDING_DETAIL_NET_BUFFER_LIST_INFO` structure to filter NVGRE traffic.

**Comment by svinturis** [comment]
For additional references please see:
[1] "Porting NDIS 6.x Drivers to NDIS 6.40", http://msdn.microsoft.com/en-us/library/windows/hardware/dn449752(v=vs.85).aspx
[2] "Implementing an NDIS 6.40 Driver", http://msdn.microsoft.com/en-us/library/windows/hardware/dn449741(v=vs.85).aspx
[3] "Using NDIS 6.40 Data Structures", http://msdn.microsoft.com/en-us/library/windows/hardware/dn449753(v=vs.85).aspx
[4] "Compiling an NDIS 6.40 Driver", http://msdn.microsoft.com/en-us/library/windows/hardware/dn449734(v=vs.85).aspx

**Comment by EitanEliahu** [comment]
Yes, but we still need 6.30 driver to load on Windows 2012.

**Comment by svinturis** [comment]
For OVS to load on Windows Server 2012, we need it to be an NDIS 6.30 driver. 
Indeed, we need to add the NDIS 6.40 specific code inside the required macro.

**Comment by nithinrajub** [comment]
:+1: 

All we need is:
#if (NDIS_SUPPORT_NDIS640)
... do stuff specific to NDIS 6.40 ...
#else
... do stuff specific to NDIS 6.30 ...
#endif

Also, sometimes:
#if (NDIS_SUPPORT_NDIS640)
... do new stuff specific to NDIS 6.40 ...
#endif

**Comment by svinturis** [comment]
Yes, it is correct.

**Comment by EitanEliahu** [comment]
We need to have a different project for 6.40 with a different name. Package output directory should be different too.   INF file should be updated too.
Thanks,
Eitan

**Comment by svinturis** [comment]
There is no need for a different project for 6.40.
NDIS 6.40 is supported on Windows 8.1, Windows Server 2012 R2, and later versions of Windows.
NDIS 6.30 is supported on Windows 8, Windows Server 2012, and later versions of Windows.

The current ovsext VS project has 4 build configurations defined: Win8 Debug, Win8 Release, Win8.1 Debug and Win8.1 Release. Win8 configurations will create an NDIS 6.30 driver and Win8.1 configuration an NDIS 6.40 one.

For Win8 Debug build configuration the output directory is datapath-windows\x64\Win8Debug\package.
For Win8 Release build configuration the output directory is datapath-windows\x64\Win8Release\package.
For Win8.1 Debug build configuration the output directory is datapath-windows\x64\Win8.1Debug\package.
For Win8.1 Release build configuration the output directory is datapath-windows\x64\Win8.1Release\package.

What we need to do is to change the compiler setting, NDIS640=1, only for Win8.1 Debug and Win8.1 Release configurations. For the other two configuration the current compiler setting is NDIS630=1, which will output a NDIS 6.30 compliant OVS driver.

Also, we need to update the INF file and make sure that the package project copies the correct INF into the output folder.

**Comment by EitanEliahu** [comment]
Let's remove Win8 project. So we have two Win8.1 projects for 6.30 and 6.40,

**Comment by svinturis** [comment]
Currently the ovsext project has four build configurations defined; two release configurations and two debug ones, Win8 Release, Win8.1 Release, Win8 Debug, Win8.1 Debug.

We don't need to have two VS projects. We don't need to add new files/resources or to remove as such. We just need to change a compiler setting.

Win8 build configurations, Release and Debug, will not be modified. Thus, the compiler setting NDIS630 will be set. These two configurations will create a release and/or debug version of OVS that is NDIS 6.30 compliant.

Win8.1 configurations, Release and Debug, will be modified and the NDIS640 setting will be set. In this way, after building the latter two configurations a release and/or debug version of OVS that is NDIS 6.40 compliant will be created.

To do this, the following lines need to be added to the ovsext.vcxproj:

```
<ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Win8 Release|x64'">
  <ClCompile>
    <PreprocessorDefinitions>%(PreprocessorDefinitions);NDIS_WDM=1;NDIS630=1</PreprocessorDefinitions>
  </ClCompile>
  <Midl>
    <PreprocessorDefinitions>%(PreprocessorDefinitions);NDIS_WDM=1;NDIS630=1</PreprocessorDefinitions>
  </Midl>
  <ResourceCompile>
    <PreprocessorDefinitions>%(PreprocessorDefinitions);NDIS_WDM=1;NDIS630=1</PreprocessorDefinitions>
  </ResourceCompile>
</ItemDefinitionGroup>
<ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Win8.1 Release|x64'">
  <ClCompile>
    <PreprocessorDefinitions>%(PreprocessorDefinitions);NDIS_WDM=1;NDIS640=1</PreprocessorDefinitions>
  </ClCompile>
  <Midl>
    <PreprocessorDefinitions>%(PreprocessorDefinitions);NDIS_WDM=1;NDIS640=1</PreprocessorDefinitions>
  </Midl>
  <ResourceCompile>
    <PreprocessorDefinitions>%(PreprocessorDefinitions);NDIS_WDM=1;NDIS640=1</PreprocessorDefinitions>
  </ResourceCompile>
</ItemDefinitionGroup>
<ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Win8 Debug|x64'">
  <ClCompile>
    <PreprocessorDefinitions>%(PreprocessorDefinitions);NDIS_WDM=1;NDIS630=1</PreprocessorDefinitions>
  </ClCompile>
  <Midl>
    <PreprocessorDefinitions>%(PreprocessorDefinitions);NDIS_WDM=1;NDIS630=1</PreprocessorDefinitions>
  </Midl>
  <ResourceCompile>
    <PreprocessorDefinitions>%(PreprocessorDefinitions);NDIS_WDM=1;NDIS630=1</PreprocessorDefinitions>
  </ResourceCompile>
</ItemDefinitionGroup>
<ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Win8.1 Debug|x64'">
  <ClCompile>
    <PreprocessorDefinitions>%(PreprocessorDefinitions);NDIS_WDM=1;NDIS640=1</PreprocessorDefinitions>
  </ClCompile>
  <Midl>
    <PreprocessorDefinitions>%(PreprocessorDefinitions);NDIS_WDM=1;NDIS640=1</PreprocessorDefinitions>
  </Midl>
  <ResourceCompile>
    <PreprocessorDefinitions>%(PreprocessorDefinitions);NDIS_WDM=1;NDIS640=1</PreprocessorDefinitions>
  </ResourceCompile>
</ItemDefinitionGroup>
```

**Comment by svinturis** [comment]
Issue solved by the indicated commit.
