### ISSUE TITLE
Create multiple tags for memory pools

### ISSUE THREAD

**Issue by aserdean** [openvswitch/ovs-issues#56]
We should have at least two tags for memory pools for easier investigation if a memory corruption occurs.

If someone has other ideas in how to better tag the allocation pools feel free too discuss.

**Comment by EitanEliahu** [comment]
Yes, Alin. Probably, a tag for memory allocated during initialization and another one for memory allocated at run time at the fast path.
That said, please note that a stack trace is available when Verfier detects memory leak. (During investigation we should replace inline memory allocation function with a standard function call)

**Comment by svinturis** [comment]
This issue was fixed. Closing it.
