### ISSUE TITLE
Flow Policy needs to be updated with new behaviour

### ISSUE THREAD

**Issue by aserdean** [openvswitch/ovs-issues#59]
On windows datapath we have the flow policy defined as the following:
/\* For Parsing attributes in FLOW_\* commands _/
const NL_POLICY nlFlowPolicy[] = {
    [OVS_FLOW_ATTR_KEY] = {.type = NL_A_NESTED, .optional = FALSE},
    [OVS_FLOW_ATTR_MASK] = {.type = NL_A_NESTED, .optional = TRUE},
    [OVS_FLOW_ATTR_ACTIONS] = {.type = NL_A_NESTED, .optional = TRUE},
    [OVS_FLOW_ATTR_STATS] = {.type = NL_A_UNSPEC,
                             .minLen = sizeof(struct ovs_flow_stats),
                             .maxLen = sizeof(struct ovs_flow_stats),
                             .optional = TRUE},
    [OVS_FLOW_ATTR_TCP_FLAGS] = {NL_A_U8, .optional = TRUE},
    [OVS_FLOW_ATTR_USED] = {NL_A_U64, .optional = TRUE}
};
On linux since commit https://github.com/openvswitch/ovs/commit/70e5ed6f39f02e1b378908f045d4ba2ab2000513
we have the following:
static const struct nl_policy ovs_flow_policy[__OVS_FLOW_ATTR_MAX] = {
    [OVS_FLOW_ATTR_KEY] = { .type = NL_A_NESTED, .optional = true },
    [OVS_FLOW_ATTR_MASK] = { .type = NL_A_NESTED, .optional = true },
    [OVS_FLOW_ATTR_ACTIONS] = { .type = NL_A_NESTED, .optional = true },
    [OVS_FLOW_ATTR_STATS] = { NL_POLICY_FOR(struct ovs_flow_stats),
                              .optional = true },
    [OVS_FLOW_ATTR_TCP_FLAGS] = { .type = NL_A_U8, .optional = true },
    [OVS_FLOW_ATTR_USED] = { .type = NL_A_U64, .optional = true },
    [OVS_FLOW_ATTR_UFID] = { .type = NL_A_UNSPEC, .optional = true,
                             .min_len = sizeof(ovs_u128) },
    /_ The kernel never uses OVS_FLOW_ATTR_CLEAR. _/
    /_ The kernel never uses OVS_FLOW_ATTR_PROBE. _/
    /_ The kernel never uses OVS_FLOW_ATTR_UFID_FLAGS. */
}; 

```
We should align to the new policy and implement the new functionality in the windows counterpart.

Unfortunately this issue is a blocker because we cannot test properly unless we revert to an outdated userspace component.
```

**Comment by EitanEliahu** [comment]
Alin, 
I just talked to Ben. The issue should be filed against user mode as it breaks the current driver. Attributes that were optional cannot be forced as it breaks the kernel.

**Comment by aserdean** [comment]
Eitan,
Should I move this issue to https://github.com/openvswitch/ovs ?

**Comment by blp** [comment]
Alin: I think it's better to leave it here. I think that I'm going to turn off the issues tracker in the main ovs repository and move the remaining issues here.
