### ISSUE TITLE
BSOD when uninstalling the driver

### ISSUE THREAD

**Issue by aserdean** [openvswitch/ovs-issues#6]
This issue happens when trying to uninstall the driver while there is active 
traffic through the switch.

Steps to reproduce:
ovs-vsctl --db=tcp:127.0.0.1:8777 add-br br0
ovs-vsctl --db=tcp:127.0.0.1:8777 add-port br0 external.1
ovs-vsctl --db=tcp:127.0.0.1:8777 add-port br0 internal
ovs-vsctl --db=tcp:127.0.0.1:8777 add-port br0 vmNICSyn.1000048
ovs-vsctl --db=tcp:127.0.0.1:8777 add-port br0 vmNICSyn.1000049

Issue uninstall.cmd while ovs-vswitchd is running and traffic is generated 
through the VM.

Here is the stack trace and Bugcheck Analysis.
http://pastebin.com/tkMr3FaD

**Comment by nithinrajub** [comment]
I don't think we have tried this configuration. Thanks for reporting this.

**Comment by EitanEliahu** [comment]
The driver will never get unloaded when a process hold an open handle to a device created by the driver. But, we must acquire dpLockState when freeing the flow table entries and to check the head variable for NULL. The driver won't get unloaded until vswitchd is terminated but it won't carsh the system.

**Comment by svinturis** [comment]
This bug does not reproduces anymore.
