### ISSUE TITLE
Set manager functionality

### ISSUE THREAD

**Issue by aserdean** [openvswitch/ovs-issues#63]
For OpenDaylight preparations we should implement in netdev-windows.c the following functions:
netdev_get_next_hop
netdev_arp_lookup

This will allow us to set the manager on the ovsdb.

**Comment by nithinrajub** [comment]
Alin, presumably this is the route lookup, and arp resolution. It should be possible to support this. The information is already available in the IP helper module.

**Comment by aserdean** [comment]
Closed with commit: https://github.com/openvswitch/ovs/commit/694ebbc85eb164a83926ace56a4d8b90424a5447
