### ISSUE TITLE
datapath-windows: Add an FWPM_PROVIDER  provider to OVS

### ISSUE THREAD

**Issue by svinturis** [openvswitch/ovs-issues#65]
I have executed the WHCK logo tests against the OVS driver and the "WindowsFilteringPlatform_Tests" tests fail. The only test that fails is "WFP-based products must create and maintain at least 1 identifying FWPM_PROVIDER provider object".

The test output is:

```
[Has an identifying Provider: FALSE]
...
FwpmProviders_MaintainIdentifying FwpmProviders.MaintainIdentifying: 0 Acceptable Providers found.
```

**Comment by EitanEliahu** [comment]
Sorin, thank you so much for running the WHCK test. Have you run the other two tests as well:
Filter.Driver.Fundamentals
Filter.Driver.Security

Do you intend to submit test results to Microsoft?
Eitan

**Comment by svinturis** [comment]
Eitan, all the other WFP-based tests for Hyper-V are passing. This is the only one that is failing.

We won't submit the tests now. For now, we are just testing the OVS to see how is behaving when running logo tests.

**Comment by svinturis** [comment]
For the OVSExt driver, Filter.Driver.Security tests are executed at "TDI filters and LSPs are not allowed" and Filter.Driver.Fundamentals tests at "Sleep and PNP (disable and enable) with IO Before and After".

The "TDI filters and LSPs are not allowed" tests suite are PASSED.
The "Sleep and PNP (disable and enable) with IO Before and After" tests suite were not fully executed yet due to an envionment configuration issue that breaks the tests execution, which I am trying to solve.
