### ISSUE TITLE
Install.Windows.md: Add details about the list of files and directories required on the Hyper-V host

### ISSUE THREAD

**Issue by mantri** [openvswitch/ovs-issues#76]
The documentation to create the Makefile is:

% ./configure CC=./build-aux/cccl LD="which link" LIBS="-lws2_32" \ --prefix="C:/openvswitch/usr" --localstatedir="C:/openvswitch/var" \ --sysconfdir="C:/openvswitch/etc" --with-pthread="C:/pthread" \ --enable-ssl --with-openssl="C:/OpenSSL-Win32" \ --with-vstudioddk=""

However, there is no mention of how the C:/openvswitch/<usr/var/etc>  etc get created. Since they don't seem to be autocreated today,  they should be either documented or somehow create them in install.cmd (I am not sure how)

The doc, as of today, indicates the following files need to be copied to the host:

./datapath-windows/x64/Win8.1Debug/package/ovsext.inf
./datapath-windows/x64/Win8.1Debug/package/OVSExt.sys
./datapath-windows/x64/Win8.1Debug/package/ovsext.cat
./datapath-windows/misc/install.cmd
./datapath-windows/misc/uninstall.cmd

Please also mention about the necessary .dll files (such as PthreadVC2.dll) needed to run the OVS utilities and other .exe files.

**Comment by nithinrajub** [comment]
Addressed in a series of commits from Gurucharan Shetty and Nithin Raju.
