### ISSUE TITLE
Issuing uninstall.cmd hangs after setting up a vxlan tunnel

### ISSUE THREAD

**Issue by aserdean** [openvswitch/ovs-issues#8]
This issue happens after setting up a tunnel between two hypervisors and
generating traffic through the VM endpoints.

Steps to reproduce:
- Set-up a tunnel between the hypervisors.
- Generate traffic between two VM's on each hypervisor
- Issue an uninstall.cmd. 
- This will lead to netcfg to hang indefinitely
- staying in just:
  c:\package\binaries>netcfg -u OVSExt
  Trying to uninstall OVSExt ...

**Comment by nithinrajub** [comment]
Is this a release build or a debug build? If it is a release build, it is possible that we hit the ASSERT(FALSE) case in OvsPacketIO.c in L221, and thus leaked NBLs. If we leaked NBLs, uninstallation will hang.

Can you pls. confirm?

**Comment by aserdean** [comment]
Release build

**Comment by nithinrajub** [comment]
Thanks Alin. In that case, this is a duplicate of:
https://github.com/openvswitch/ovs-issues/issues/10
