### ISSUE TITLE
Disabling and re-enabling the OVS extension does not permit userspace to open handles

### ISSUE THREAD

**Issue by nithinrajub** [openvswitch/ovs-issues#86]
After installing the OVS extension, and enabling the extension on the Hyper-V switch, userspace daemons are able to create handles. Disabling and re-enabling the extension (without uninstall/reinstall), causes and issue, where the userspace processes cannot open handles anymore.

Running dpctl show, throws the error:
$ utilities/ovs-dpctl.exe show
2015-06-19T03:11:44Z|00001|dpif|WARN|failed to enumerate system datapaths: Invalid argument

This seems like a regression, since it was working earlier.

**Comment by svinturis** [comment]
Issue solved by the above patch. Closed.
